// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.29.1

package hla.rti1516_2025.fedpro;

public interface AssociateRegionsForUpdatesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2025.fedpro.AssociateRegionsForUpdatesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2025.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   * @return Whether the objectInstance field is set.
   */
  boolean hasObjectInstance();
  /**
   * <code>.rti1516_2025.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   * @return The objectInstance.
   */
  hla.rti1516_2025.fedpro.ObjectInstanceHandle getObjectInstance();
  /**
   * <code>.rti1516_2025.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   */
  hla.rti1516_2025.fedpro.ObjectInstanceHandleOrBuilder getObjectInstanceOrBuilder();

  /**
   * <code>.rti1516_2025.fedpro.AttributeSetRegionSetPairList attributesAndRegions = 2;</code>
   * @return Whether the attributesAndRegions field is set.
   */
  boolean hasAttributesAndRegions();
  /**
   * <code>.rti1516_2025.fedpro.AttributeSetRegionSetPairList attributesAndRegions = 2;</code>
   * @return The attributesAndRegions.
   */
  hla.rti1516_2025.fedpro.AttributeSetRegionSetPairList getAttributesAndRegions();
  /**
   * <code>.rti1516_2025.fedpro.AttributeSetRegionSetPairList attributesAndRegions = 2;</code>
   */
  hla.rti1516_2025.fedpro.AttributeSetRegionSetPairListOrBuilder getAttributesAndRegionsOrBuilder();
}
