// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.29.1

package hla.rti1516_2025.fedpro;

public interface ParameterHandleValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2025.fedpro.ParameterHandleValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2025.fedpro.ParameterHandle parameterHandle = 1;</code>
   * @return Whether the parameterHandle field is set.
   */
  boolean hasParameterHandle();
  /**
   * <code>.rti1516_2025.fedpro.ParameterHandle parameterHandle = 1;</code>
   * @return The parameterHandle.
   */
  hla.rti1516_2025.fedpro.ParameterHandle getParameterHandle();
  /**
   * <code>.rti1516_2025.fedpro.ParameterHandle parameterHandle = 1;</code>
   */
  hla.rti1516_2025.fedpro.ParameterHandleOrBuilder getParameterHandleOrBuilder();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
