// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.29.1

package hla.rti1516_2025.fedpro;

public interface QueryInteractionTransportationTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2025.fedpro.QueryInteractionTransportationTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2025.fedpro.FederateHandle federate = 1;</code>
   * @return Whether the federate field is set.
   */
  boolean hasFederate();
  /**
   * <code>.rti1516_2025.fedpro.FederateHandle federate = 1;</code>
   * @return The federate.
   */
  hla.rti1516_2025.fedpro.FederateHandle getFederate();
  /**
   * <code>.rti1516_2025.fedpro.FederateHandle federate = 1;</code>
   */
  hla.rti1516_2025.fedpro.FederateHandleOrBuilder getFederateOrBuilder();

  /**
   * <code>.rti1516_2025.fedpro.InteractionClassHandle interactionClass = 2;</code>
   * @return Whether the interactionClass field is set.
   */
  boolean hasInteractionClass();
  /**
   * <code>.rti1516_2025.fedpro.InteractionClassHandle interactionClass = 2;</code>
   * @return The interactionClass.
   */
  hla.rti1516_2025.fedpro.InteractionClassHandle getInteractionClass();
  /**
   * <code>.rti1516_2025.fedpro.InteractionClassHandle interactionClass = 2;</code>
   */
  hla.rti1516_2025.fedpro.InteractionClassHandleOrBuilder getInteractionClassOrBuilder();
}
