// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.29.1

package hla.rti1516_2025.fedpro;

public interface RequestFederationRestoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2025.fedpro.RequestFederationRestoreResponse)
    com.google.protobuf.MessageOrBuilder {
}
