// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.29.1

package hla.rti1516_2025.fedpro;

public interface SendInteractionWithRegionsAndTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2025.fedpro.SendInteractionWithRegionsAndTimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2025.fedpro.InteractionClassHandle interactionClass = 1;</code>
   * @return Whether the interactionClass field is set.
   */
  boolean hasInteractionClass();
  /**
   * <code>.rti1516_2025.fedpro.InteractionClassHandle interactionClass = 1;</code>
   * @return The interactionClass.
   */
  hla.rti1516_2025.fedpro.InteractionClassHandle getInteractionClass();
  /**
   * <code>.rti1516_2025.fedpro.InteractionClassHandle interactionClass = 1;</code>
   */
  hla.rti1516_2025.fedpro.InteractionClassHandleOrBuilder getInteractionClassOrBuilder();

  /**
   * <code>.rti1516_2025.fedpro.ParameterHandleValueMap parameterValues = 2;</code>
   * @return Whether the parameterValues field is set.
   */
  boolean hasParameterValues();
  /**
   * <code>.rti1516_2025.fedpro.ParameterHandleValueMap parameterValues = 2;</code>
   * @return The parameterValues.
   */
  hla.rti1516_2025.fedpro.ParameterHandleValueMap getParameterValues();
  /**
   * <code>.rti1516_2025.fedpro.ParameterHandleValueMap parameterValues = 2;</code>
   */
  hla.rti1516_2025.fedpro.ParameterHandleValueMapOrBuilder getParameterValuesOrBuilder();

  /**
   * <code>.rti1516_2025.fedpro.RegionHandleSet regions = 3;</code>
   * @return Whether the regions field is set.
   */
  boolean hasRegions();
  /**
   * <code>.rti1516_2025.fedpro.RegionHandleSet regions = 3;</code>
   * @return The regions.
   */
  hla.rti1516_2025.fedpro.RegionHandleSet getRegions();
  /**
   * <code>.rti1516_2025.fedpro.RegionHandleSet regions = 3;</code>
   */
  hla.rti1516_2025.fedpro.RegionHandleSetOrBuilder getRegionsOrBuilder();

  /**
   * <code>bytes userSuppliedTag = 4;</code>
   * @return The userSuppliedTag.
   */
  com.google.protobuf.ByteString getUserSuppliedTag();

  /**
   * <code>.rti1516_2025.fedpro.LogicalTime time = 5;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <code>.rti1516_2025.fedpro.LogicalTime time = 5;</code>
   * @return The time.
   */
  hla.rti1516_2025.fedpro.LogicalTime getTime();
  /**
   * <code>.rti1516_2025.fedpro.LogicalTime time = 5;</code>
   */
  hla.rti1516_2025.fedpro.LogicalTimeOrBuilder getTimeOrBuilder();
}
