// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.29.1

package hla.rti1516_2025.fedpro;

public interface TimeAdvanceRequestAvailableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2025.fedpro.TimeAdvanceRequestAvailableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2025.fedpro.LogicalTime time = 1;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <code>.rti1516_2025.fedpro.LogicalTime time = 1;</code>
   * @return The time.
   */
  hla.rti1516_2025.fedpro.LogicalTime getTime();
  /**
   * <code>.rti1516_2025.fedpro.LogicalTime time = 1;</code>
   */
  hla.rti1516_2025.fedpro.LogicalTimeOrBuilder getTimeOrBuilder();
}
