// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

/**
 * Protobuf type {@code thinhla.CreateFederationExecutionRequest}
 */
public final class CreateFederationExecutionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:thinhla.CreateFederationExecutionRequest)
    CreateFederationExecutionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateFederationExecutionRequest.newBuilder() to construct.
  private CreateFederationExecutionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateFederationExecutionRequest() {
    federationExecutionName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateFederationExecutionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hla.rti1516_202X.thin.ThinRTIambassador.internal_static_thinhla_CreateFederationExecutionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hla.rti1516_202X.thin.ThinRTIambassador.internal_static_thinhla_CreateFederationExecutionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hla.rti1516_202X.thin.CreateFederationExecutionRequest.class, hla.rti1516_202X.thin.CreateFederationExecutionRequest.Builder.class);
  }

  public static final int FEDERATIONEXECUTIONNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object federationExecutionName_;
  /**
   * <code>string federationExecutionName = 1;</code>
   * @return The federationExecutionName.
   */
  @java.lang.Override
  public java.lang.String getFederationExecutionName() {
    java.lang.Object ref = federationExecutionName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      federationExecutionName_ = s;
      return s;
    }
  }
  /**
   * <code>string federationExecutionName = 1;</code>
   * @return The bytes for federationExecutionName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFederationExecutionNameBytes() {
    java.lang.Object ref = federationExecutionName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      federationExecutionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOMMODULE_FIELD_NUMBER = 2;
  private hla.rti1516_202X.thin.FomModule fomModule_;
  /**
   * <code>.thinhla.FomModule fomModule = 2;</code>
   * @return Whether the fomModule field is set.
   */
  @java.lang.Override
  public boolean hasFomModule() {
    return fomModule_ != null;
  }
  /**
   * <code>.thinhla.FomModule fomModule = 2;</code>
   * @return The fomModule.
   */
  @java.lang.Override
  public hla.rti1516_202X.thin.FomModule getFomModule() {
    return fomModule_ == null ? hla.rti1516_202X.thin.FomModule.getDefaultInstance() : fomModule_;
  }
  /**
   * <code>.thinhla.FomModule fomModule = 2;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.thin.FomModuleOrBuilder getFomModuleOrBuilder() {
    return getFomModule();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(federationExecutionName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, federationExecutionName_);
    }
    if (fomModule_ != null) {
      output.writeMessage(2, getFomModule());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(federationExecutionName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, federationExecutionName_);
    }
    if (fomModule_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFomModule());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hla.rti1516_202X.thin.CreateFederationExecutionRequest)) {
      return super.equals(obj);
    }
    hla.rti1516_202X.thin.CreateFederationExecutionRequest other = (hla.rti1516_202X.thin.CreateFederationExecutionRequest) obj;

    if (!getFederationExecutionName()
        .equals(other.getFederationExecutionName())) return false;
    if (hasFomModule() != other.hasFomModule()) return false;
    if (hasFomModule()) {
      if (!getFomModule()
          .equals(other.getFomModule())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FEDERATIONEXECUTIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFederationExecutionName().hashCode();
    if (hasFomModule()) {
      hash = (37 * hash) + FOMMODULE_FIELD_NUMBER;
      hash = (53 * hash) + getFomModule().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hla.rti1516_202X.thin.CreateFederationExecutionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code thinhla.CreateFederationExecutionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:thinhla.CreateFederationExecutionRequest)
      hla.rti1516_202X.thin.CreateFederationExecutionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hla.rti1516_202X.thin.ThinRTIambassador.internal_static_thinhla_CreateFederationExecutionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hla.rti1516_202X.thin.ThinRTIambassador.internal_static_thinhla_CreateFederationExecutionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hla.rti1516_202X.thin.CreateFederationExecutionRequest.class, hla.rti1516_202X.thin.CreateFederationExecutionRequest.Builder.class);
    }

    // Construct using hla.rti1516_202X.thin.CreateFederationExecutionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      federationExecutionName_ = "";

      if (fomModuleBuilder_ == null) {
        fomModule_ = null;
      } else {
        fomModule_ = null;
        fomModuleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hla.rti1516_202X.thin.ThinRTIambassador.internal_static_thinhla_CreateFederationExecutionRequest_descriptor;
    }

    @java.lang.Override
    public hla.rti1516_202X.thin.CreateFederationExecutionRequest getDefaultInstanceForType() {
      return hla.rti1516_202X.thin.CreateFederationExecutionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public hla.rti1516_202X.thin.CreateFederationExecutionRequest build() {
      hla.rti1516_202X.thin.CreateFederationExecutionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hla.rti1516_202X.thin.CreateFederationExecutionRequest buildPartial() {
      hla.rti1516_202X.thin.CreateFederationExecutionRequest result = new hla.rti1516_202X.thin.CreateFederationExecutionRequest(this);
      result.federationExecutionName_ = federationExecutionName_;
      if (fomModuleBuilder_ == null) {
        result.fomModule_ = fomModule_;
      } else {
        result.fomModule_ = fomModuleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hla.rti1516_202X.thin.CreateFederationExecutionRequest) {
        return mergeFrom((hla.rti1516_202X.thin.CreateFederationExecutionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hla.rti1516_202X.thin.CreateFederationExecutionRequest other) {
      if (other == hla.rti1516_202X.thin.CreateFederationExecutionRequest.getDefaultInstance()) return this;
      if (!other.getFederationExecutionName().isEmpty()) {
        federationExecutionName_ = other.federationExecutionName_;
        onChanged();
      }
      if (other.hasFomModule()) {
        mergeFomModule(other.getFomModule());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              federationExecutionName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getFomModuleFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object federationExecutionName_ = "";
    /**
     * <code>string federationExecutionName = 1;</code>
     * @return The federationExecutionName.
     */
    public java.lang.String getFederationExecutionName() {
      java.lang.Object ref = federationExecutionName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        federationExecutionName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string federationExecutionName = 1;</code>
     * @return The bytes for federationExecutionName.
     */
    public com.google.protobuf.ByteString
        getFederationExecutionNameBytes() {
      java.lang.Object ref = federationExecutionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        federationExecutionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string federationExecutionName = 1;</code>
     * @param value The federationExecutionName to set.
     * @return This builder for chaining.
     */
    public Builder setFederationExecutionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      federationExecutionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string federationExecutionName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFederationExecutionName() {
      
      federationExecutionName_ = getDefaultInstance().getFederationExecutionName();
      onChanged();
      return this;
    }
    /**
     * <code>string federationExecutionName = 1;</code>
     * @param value The bytes for federationExecutionName to set.
     * @return This builder for chaining.
     */
    public Builder setFederationExecutionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      federationExecutionName_ = value;
      onChanged();
      return this;
    }

    private hla.rti1516_202X.thin.FomModule fomModule_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.thin.FomModule, hla.rti1516_202X.thin.FomModule.Builder, hla.rti1516_202X.thin.FomModuleOrBuilder> fomModuleBuilder_;
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     * @return Whether the fomModule field is set.
     */
    public boolean hasFomModule() {
      return fomModuleBuilder_ != null || fomModule_ != null;
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     * @return The fomModule.
     */
    public hla.rti1516_202X.thin.FomModule getFomModule() {
      if (fomModuleBuilder_ == null) {
        return fomModule_ == null ? hla.rti1516_202X.thin.FomModule.getDefaultInstance() : fomModule_;
      } else {
        return fomModuleBuilder_.getMessage();
      }
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    public Builder setFomModule(hla.rti1516_202X.thin.FomModule value) {
      if (fomModuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fomModule_ = value;
        onChanged();
      } else {
        fomModuleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    public Builder setFomModule(
        hla.rti1516_202X.thin.FomModule.Builder builderForValue) {
      if (fomModuleBuilder_ == null) {
        fomModule_ = builderForValue.build();
        onChanged();
      } else {
        fomModuleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    public Builder mergeFomModule(hla.rti1516_202X.thin.FomModule value) {
      if (fomModuleBuilder_ == null) {
        if (fomModule_ != null) {
          fomModule_ =
            hla.rti1516_202X.thin.FomModule.newBuilder(fomModule_).mergeFrom(value).buildPartial();
        } else {
          fomModule_ = value;
        }
        onChanged();
      } else {
        fomModuleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    public Builder clearFomModule() {
      if (fomModuleBuilder_ == null) {
        fomModule_ = null;
        onChanged();
      } else {
        fomModule_ = null;
        fomModuleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    public hla.rti1516_202X.thin.FomModule.Builder getFomModuleBuilder() {
      
      onChanged();
      return getFomModuleFieldBuilder().getBuilder();
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    public hla.rti1516_202X.thin.FomModuleOrBuilder getFomModuleOrBuilder() {
      if (fomModuleBuilder_ != null) {
        return fomModuleBuilder_.getMessageOrBuilder();
      } else {
        return fomModule_ == null ?
            hla.rti1516_202X.thin.FomModule.getDefaultInstance() : fomModule_;
      }
    }
    /**
     * <code>.thinhla.FomModule fomModule = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.thin.FomModule, hla.rti1516_202X.thin.FomModule.Builder, hla.rti1516_202X.thin.FomModuleOrBuilder> 
        getFomModuleFieldBuilder() {
      if (fomModuleBuilder_ == null) {
        fomModuleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.thin.FomModule, hla.rti1516_202X.thin.FomModule.Builder, hla.rti1516_202X.thin.FomModuleOrBuilder>(
                getFomModule(),
                getParentForChildren(),
                isClean());
        fomModule_ = null;
      }
      return fomModuleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:thinhla.CreateFederationExecutionRequest)
  }

  // @@protoc_insertion_point(class_scope:thinhla.CreateFederationExecutionRequest)
  private static final hla.rti1516_202X.thin.CreateFederationExecutionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hla.rti1516_202X.thin.CreateFederationExecutionRequest();
  }

  public static hla.rti1516_202X.thin.CreateFederationExecutionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateFederationExecutionRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateFederationExecutionRequest>() {
    @java.lang.Override
    public CreateFederationExecutionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateFederationExecutionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateFederationExecutionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hla.rti1516_202X.thin.CreateFederationExecutionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

