// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface FederateSaveBegunRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.FederateSaveBegunRequest)
    com.google.protobuf.MessageOrBuilder {
}
