// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface GetAvailableDimensionsForClassAttributeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.GetAvailableDimensionsForClassAttributeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.ObjectClassHandle whichClass = 1;</code>
   * @return Whether the whichClass field is set.
   */
  boolean hasWhichClass();
  /**
   * <code>.thinhla.ObjectClassHandle whichClass = 1;</code>
   * @return The whichClass.
   */
  hla.rti1516_202X.thin.ObjectClassHandle getWhichClass();
  /**
   * <code>.thinhla.ObjectClassHandle whichClass = 1;</code>
   */
  hla.rti1516_202X.thin.ObjectClassHandleOrBuilder getWhichClassOrBuilder();

  /**
   * <code>.thinhla.AttributeHandle theHandle = 2;</code>
   * @return Whether the theHandle field is set.
   */
  boolean hasTheHandle();
  /**
   * <code>.thinhla.AttributeHandle theHandle = 2;</code>
   * @return The theHandle.
   */
  hla.rti1516_202X.thin.AttributeHandle getTheHandle();
  /**
   * <code>.thinhla.AttributeHandle theHandle = 2;</code>
   */
  hla.rti1516_202X.thin.AttributeHandleOrBuilder getTheHandleOrBuilder();
}
