// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface GetOrderNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.GetOrderNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.OrderType theType = 1;</code>
   * @return The enum numeric value on the wire for theType.
   */
  int getTheTypeValue();
  /**
   * <code>.thinhla.OrderType theType = 1;</code>
   * @return The theType.
   */
  hla.rti1516_202X.thin.OrderType getTheType();
}
