// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FederateAmbassador.proto

package hla.rti1516_202X.thin;

/**
 * Protobuf type {@code thinhla.ObjectInstanceNameReservationSucceeded}
 */
public final class ObjectInstanceNameReservationSucceeded extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:thinhla.ObjectInstanceNameReservationSucceeded)
    ObjectInstanceNameReservationSucceededOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ObjectInstanceNameReservationSucceeded.newBuilder() to construct.
  private ObjectInstanceNameReservationSucceeded(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ObjectInstanceNameReservationSucceeded() {
    objectName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ObjectInstanceNameReservationSucceeded();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hla.rti1516_202X.thin.ThinFederateAmbassador.internal_static_thinhla_ObjectInstanceNameReservationSucceeded_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hla.rti1516_202X.thin.ThinFederateAmbassador.internal_static_thinhla_ObjectInstanceNameReservationSucceeded_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.class, hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.Builder.class);
  }

  public static final int OBJECTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object objectName_;
  /**
   * <code>string objectName = 1;</code>
   * @return The objectName.
   */
  @java.lang.Override
  public java.lang.String getObjectName() {
    java.lang.Object ref = objectName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectName_ = s;
      return s;
    }
  }
  /**
   * <code>string objectName = 1;</code>
   * @return The bytes for objectName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectNameBytes() {
    java.lang.Object ref = objectName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded)) {
      return super.equals(obj);
    }
    hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded other = (hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded) obj;

    if (!getObjectName()
        .equals(other.getObjectName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getObjectName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code thinhla.ObjectInstanceNameReservationSucceeded}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:thinhla.ObjectInstanceNameReservationSucceeded)
      hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceededOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hla.rti1516_202X.thin.ThinFederateAmbassador.internal_static_thinhla_ObjectInstanceNameReservationSucceeded_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hla.rti1516_202X.thin.ThinFederateAmbassador.internal_static_thinhla_ObjectInstanceNameReservationSucceeded_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.class, hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.Builder.class);
    }

    // Construct using hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      objectName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hla.rti1516_202X.thin.ThinFederateAmbassador.internal_static_thinhla_ObjectInstanceNameReservationSucceeded_descriptor;
    }

    @java.lang.Override
    public hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded getDefaultInstanceForType() {
      return hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.getDefaultInstance();
    }

    @java.lang.Override
    public hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded build() {
      hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded buildPartial() {
      hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded result = new hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded(this);
      result.objectName_ = objectName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded) {
        return mergeFrom((hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded other) {
      if (other == hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded.getDefaultInstance()) return this;
      if (!other.getObjectName().isEmpty()) {
        objectName_ = other.objectName_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              objectName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object objectName_ = "";
    /**
     * <code>string objectName = 1;</code>
     * @return The objectName.
     */
    public java.lang.String getObjectName() {
      java.lang.Object ref = objectName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string objectName = 1;</code>
     * @return The bytes for objectName.
     */
    public com.google.protobuf.ByteString
        getObjectNameBytes() {
      java.lang.Object ref = objectName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string objectName = 1;</code>
     * @param value The objectName to set.
     * @return This builder for chaining.
     */
    public Builder setObjectName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string objectName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectName() {
      
      objectName_ = getDefaultInstance().getObjectName();
      onChanged();
      return this;
    }
    /**
     * <code>string objectName = 1;</code>
     * @param value The bytes for objectName to set.
     * @return This builder for chaining.
     */
    public Builder setObjectNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:thinhla.ObjectInstanceNameReservationSucceeded)
  }

  // @@protoc_insertion_point(class_scope:thinhla.ObjectInstanceNameReservationSucceeded)
  private static final hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded();
  }

  public static hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ObjectInstanceNameReservationSucceeded>
      PARSER = new com.google.protobuf.AbstractParser<ObjectInstanceNameReservationSucceeded>() {
    @java.lang.Override
    public ObjectInstanceNameReservationSucceeded parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ObjectInstanceNameReservationSucceeded> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ObjectInstanceNameReservationSucceeded> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hla.rti1516_202X.thin.ObjectInstanceNameReservationSucceeded getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

