// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FederateAmbassador.proto

package hla.rti1516_202X.thin;

public interface ReportFederationExecutionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.ReportFederationExecutions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.FederationExecutionInformationSet theFederationExecutionInformationSet = 1;</code>
   * @return Whether the theFederationExecutionInformationSet field is set.
   */
  boolean hasTheFederationExecutionInformationSet();
  /**
   * <code>.thinhla.FederationExecutionInformationSet theFederationExecutionInformationSet = 1;</code>
   * @return The theFederationExecutionInformationSet.
   */
  hla.rti1516_202X.thin.FederationExecutionInformationSet getTheFederationExecutionInformationSet();
  /**
   * <code>.thinhla.FederationExecutionInformationSet theFederationExecutionInformationSet = 1;</code>
   */
  hla.rti1516_202X.thin.FederationExecutionInformationSetOrBuilder getTheFederationExecutionInformationSetOrBuilder();
}
