// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface RequestAttributeValueUpdateWithRegionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.RequestAttributeValueUpdateWithRegionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.ObjectClassHandle theClass = 1;</code>
   * @return Whether the theClass field is set.
   */
  boolean hasTheClass();
  /**
   * <code>.thinhla.ObjectClassHandle theClass = 1;</code>
   * @return The theClass.
   */
  hla.rti1516_202X.thin.ObjectClassHandle getTheClass();
  /**
   * <code>.thinhla.ObjectClassHandle theClass = 1;</code>
   */
  hla.rti1516_202X.thin.ObjectClassHandleOrBuilder getTheClassOrBuilder();

  /**
   * <code>.thinhla.AttributeSetRegionSetPairList attributesAndRegions = 2;</code>
   * @return Whether the attributesAndRegions field is set.
   */
  boolean hasAttributesAndRegions();
  /**
   * <code>.thinhla.AttributeSetRegionSetPairList attributesAndRegions = 2;</code>
   * @return The attributesAndRegions.
   */
  hla.rti1516_202X.thin.AttributeSetRegionSetPairList getAttributesAndRegions();
  /**
   * <code>.thinhla.AttributeSetRegionSetPairList attributesAndRegions = 2;</code>
   */
  hla.rti1516_202X.thin.AttributeSetRegionSetPairListOrBuilder getAttributesAndRegionsOrBuilder();

  /**
   * <code>bytes userSuppliedTag = 3;</code>
   * @return The userSuppliedTag.
   */
  com.google.protobuf.ByteString getUserSuppliedTag();
}
