// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.thin;

public interface RtiConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.RtiConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string configurationName = 1;</code>
   * @return The configurationName.
   */
  java.lang.String getConfigurationName();
  /**
   * <code>string configurationName = 1;</code>
   * @return The bytes for configurationName.
   */
  com.google.protobuf.ByteString
      getConfigurationNameBytes();

  /**
   * <code>string rtiAddress = 2;</code>
   * @return The rtiAddress.
   */
  java.lang.String getRtiAddress();
  /**
   * <code>string rtiAddress = 2;</code>
   * @return The bytes for rtiAddress.
   */
  com.google.protobuf.ByteString
      getRtiAddressBytes();

  /**
   * <code>string additionalSettings = 3;</code>
   * @return The additionalSettings.
   */
  java.lang.String getAdditionalSettings();
  /**
   * <code>string additionalSettings = 3;</code>
   * @return The bytes for additionalSettings.
   */
  com.google.protobuf.ByteString
      getAdditionalSettingsBytes();

  /**
   * <code>string federateProtocolServerAddress = 4;</code>
   * @return The federateProtocolServerAddress.
   */
  java.lang.String getFederateProtocolServerAddress();
  /**
   * <code>string federateProtocolServerAddress = 4;</code>
   * @return The bytes for federateProtocolServerAddress.
   */
  com.google.protobuf.ByteString
      getFederateProtocolServerAddressBytes();

  /**
   * <code>string federateProtocolAdditionalSettings = 5;</code>
   * @return The federateProtocolAdditionalSettings.
   */
  java.lang.String getFederateProtocolAdditionalSettings();
  /**
   * <code>string federateProtocolAdditionalSettings = 5;</code>
   * @return The bytes for federateProtocolAdditionalSettings.
   */
  com.google.protobuf.ByteString
      getFederateProtocolAdditionalSettingsBytes();
}
