// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface SetAutomaticResignDirectiveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.SetAutomaticResignDirectiveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.ResignAction resignAction = 1;</code>
   * @return The enum numeric value on the wire for resignAction.
   */
  int getResignActionValue();
  /**
   * <code>.thinhla.ResignAction resignAction = 1;</code>
   * @return The resignAction.
   */
  hla.rti1516_202X.thin.ResignAction getResignAction();
}
