// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface SubscribeObjectClassAttributesPassivelyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.SubscribeObjectClassAttributesPassivelyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.ObjectClassHandle theClass = 1;</code>
   * @return Whether the theClass field is set.
   */
  boolean hasTheClass();
  /**
   * <code>.thinhla.ObjectClassHandle theClass = 1;</code>
   * @return The theClass.
   */
  hla.rti1516_202X.thin.ObjectClassHandle getTheClass();
  /**
   * <code>.thinhla.ObjectClassHandle theClass = 1;</code>
   */
  hla.rti1516_202X.thin.ObjectClassHandleOrBuilder getTheClassOrBuilder();

  /**
   * <code>.thinhla.AttributeHandleSet attributeList = 2;</code>
   * @return Whether the attributeList field is set.
   */
  boolean hasAttributeList();
  /**
   * <code>.thinhla.AttributeHandleSet attributeList = 2;</code>
   * @return The attributeList.
   */
  hla.rti1516_202X.thin.AttributeHandleSet getAttributeList();
  /**
   * <code>.thinhla.AttributeHandleSet attributeList = 2;</code>
   */
  hla.rti1516_202X.thin.AttributeHandleSetOrBuilder getAttributeListOrBuilder();
}
