// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.thin;

public interface UpdateAttributeValuesWithTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thinhla.UpdateAttributeValuesWithTimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.thinhla.ObjectInstanceHandle theObject = 1;</code>
   * @return Whether the theObject field is set.
   */
  boolean hasTheObject();
  /**
   * <code>.thinhla.ObjectInstanceHandle theObject = 1;</code>
   * @return The theObject.
   */
  hla.rti1516_202X.thin.ObjectInstanceHandle getTheObject();
  /**
   * <code>.thinhla.ObjectInstanceHandle theObject = 1;</code>
   */
  hla.rti1516_202X.thin.ObjectInstanceHandleOrBuilder getTheObjectOrBuilder();

  /**
   * <code>.thinhla.AttributeHandleValueMap theAttributes = 2;</code>
   * @return Whether the theAttributes field is set.
   */
  boolean hasTheAttributes();
  /**
   * <code>.thinhla.AttributeHandleValueMap theAttributes = 2;</code>
   * @return The theAttributes.
   */
  hla.rti1516_202X.thin.AttributeHandleValueMap getTheAttributes();
  /**
   * <code>.thinhla.AttributeHandleValueMap theAttributes = 2;</code>
   */
  hla.rti1516_202X.thin.AttributeHandleValueMapOrBuilder getTheAttributesOrBuilder();

  /**
   * <code>bytes userSuppliedTag = 3;</code>
   * @return The userSuppliedTag.
   */
  com.google.protobuf.ByteString getUserSuppliedTag();

  /**
   * <code>.thinhla.LogicalTime theTime = 4;</code>
   * @return Whether the theTime field is set.
   */
  boolean hasTheTime();
  /**
   * <code>.thinhla.LogicalTime theTime = 4;</code>
   * @return The theTime.
   */
  hla.rti1516_202X.thin.LogicalTime getTheTime();
  /**
   * <code>.thinhla.LogicalTime theTime = 4;</code>
   */
  hla.rti1516_202X.thin.LogicalTimeOrBuilder getTheTimeOrBuilder();
}
