// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.fedpro;

/**
 * <pre>
 * Map with AttributeHandle as key.
 * The map shall not contain duplicate keys.
 * </pre>
 *
 * Protobuf type {@code rti1516_202X.fedpro.AttributeHandleValueMap}
 */
public final class AttributeHandleValueMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti1516_202X.fedpro.AttributeHandleValueMap)
    AttributeHandleValueMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AttributeHandleValueMap.newBuilder() to construct.
  private AttributeHandleValueMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AttributeHandleValueMap() {
    attributeHandleValue_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AttributeHandleValueMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_AttributeHandleValueMap_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_AttributeHandleValueMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hla.rti1516_202X.fedpro.AttributeHandleValueMap.class, hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder.class);
  }

  public static final int ATTRIBUTEHANDLEVALUE_FIELD_NUMBER = 1;
  private java.util.List<hla.rti1516_202X.fedpro.AttributeHandleValue> attributeHandleValue_;
  /**
   * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  @java.lang.Override
  public java.util.List<hla.rti1516_202X.fedpro.AttributeHandleValue> getAttributeHandleValueList() {
    return attributeHandleValue_;
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder> 
      getAttributeHandleValueOrBuilderList() {
    return attributeHandleValue_;
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  @java.lang.Override
  public int getAttributeHandleValueCount() {
    return attributeHandleValue_.size();
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.AttributeHandleValue getAttributeHandleValue(int index) {
    return attributeHandleValue_.get(index);
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder getAttributeHandleValueOrBuilder(
      int index) {
    return attributeHandleValue_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < attributeHandleValue_.size(); i++) {
      output.writeMessage(1, attributeHandleValue_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < attributeHandleValue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, attributeHandleValue_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hla.rti1516_202X.fedpro.AttributeHandleValueMap)) {
      return super.equals(obj);
    }
    hla.rti1516_202X.fedpro.AttributeHandleValueMap other = (hla.rti1516_202X.fedpro.AttributeHandleValueMap) obj;

    if (!getAttributeHandleValueList()
        .equals(other.getAttributeHandleValueList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAttributeHandleValueCount() > 0) {
      hash = (37 * hash) + ATTRIBUTEHANDLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeHandleValueList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hla.rti1516_202X.fedpro.AttributeHandleValueMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Map with AttributeHandle as key.
   * The map shall not contain duplicate keys.
   * </pre>
   *
   * Protobuf type {@code rti1516_202X.fedpro.AttributeHandleValueMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti1516_202X.fedpro.AttributeHandleValueMap)
      hla.rti1516_202X.fedpro.AttributeHandleValueMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_AttributeHandleValueMap_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_AttributeHandleValueMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hla.rti1516_202X.fedpro.AttributeHandleValueMap.class, hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder.class);
    }

    // Construct using hla.rti1516_202X.fedpro.AttributeHandleValueMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (attributeHandleValueBuilder_ == null) {
        attributeHandleValue_ = java.util.Collections.emptyList();
      } else {
        attributeHandleValue_ = null;
        attributeHandleValueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_AttributeHandleValueMap_descriptor;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.AttributeHandleValueMap getDefaultInstanceForType() {
      return hla.rti1516_202X.fedpro.AttributeHandleValueMap.getDefaultInstance();
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.AttributeHandleValueMap build() {
      hla.rti1516_202X.fedpro.AttributeHandleValueMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.AttributeHandleValueMap buildPartial() {
      hla.rti1516_202X.fedpro.AttributeHandleValueMap result = new hla.rti1516_202X.fedpro.AttributeHandleValueMap(this);
      int from_bitField0_ = bitField0_;
      if (attributeHandleValueBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          attributeHandleValue_ = java.util.Collections.unmodifiableList(attributeHandleValue_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.attributeHandleValue_ = attributeHandleValue_;
      } else {
        result.attributeHandleValue_ = attributeHandleValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hla.rti1516_202X.fedpro.AttributeHandleValueMap) {
        return mergeFrom((hla.rti1516_202X.fedpro.AttributeHandleValueMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hla.rti1516_202X.fedpro.AttributeHandleValueMap other) {
      if (other == hla.rti1516_202X.fedpro.AttributeHandleValueMap.getDefaultInstance()) return this;
      if (attributeHandleValueBuilder_ == null) {
        if (!other.attributeHandleValue_.isEmpty()) {
          if (attributeHandleValue_.isEmpty()) {
            attributeHandleValue_ = other.attributeHandleValue_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAttributeHandleValueIsMutable();
            attributeHandleValue_.addAll(other.attributeHandleValue_);
          }
          onChanged();
        }
      } else {
        if (!other.attributeHandleValue_.isEmpty()) {
          if (attributeHandleValueBuilder_.isEmpty()) {
            attributeHandleValueBuilder_.dispose();
            attributeHandleValueBuilder_ = null;
            attributeHandleValue_ = other.attributeHandleValue_;
            bitField0_ = (bitField0_ & ~0x00000001);
            attributeHandleValueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttributeHandleValueFieldBuilder() : null;
          } else {
            attributeHandleValueBuilder_.addAllMessages(other.attributeHandleValue_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hla.rti1516_202X.fedpro.AttributeHandleValue m =
                  input.readMessage(
                      hla.rti1516_202X.fedpro.AttributeHandleValue.parser(),
                      extensionRegistry);
              if (attributeHandleValueBuilder_ == null) {
                ensureAttributeHandleValueIsMutable();
                attributeHandleValue_.add(m);
              } else {
                attributeHandleValueBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<hla.rti1516_202X.fedpro.AttributeHandleValue> attributeHandleValue_ =
      java.util.Collections.emptyList();
    private void ensureAttributeHandleValueIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        attributeHandleValue_ = new java.util.ArrayList<hla.rti1516_202X.fedpro.AttributeHandleValue>(attributeHandleValue_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        hla.rti1516_202X.fedpro.AttributeHandleValue, hla.rti1516_202X.fedpro.AttributeHandleValue.Builder, hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder> attributeHandleValueBuilder_;

    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public java.util.List<hla.rti1516_202X.fedpro.AttributeHandleValue> getAttributeHandleValueList() {
      if (attributeHandleValueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributeHandleValue_);
      } else {
        return attributeHandleValueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public int getAttributeHandleValueCount() {
      if (attributeHandleValueBuilder_ == null) {
        return attributeHandleValue_.size();
      } else {
        return attributeHandleValueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValue getAttributeHandleValue(int index) {
      if (attributeHandleValueBuilder_ == null) {
        return attributeHandleValue_.get(index);
      } else {
        return attributeHandleValueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder setAttributeHandleValue(
        int index, hla.rti1516_202X.fedpro.AttributeHandleValue value) {
      if (attributeHandleValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.set(index, value);
        onChanged();
      } else {
        attributeHandleValueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder setAttributeHandleValue(
        int index, hla.rti1516_202X.fedpro.AttributeHandleValue.Builder builderForValue) {
      if (attributeHandleValueBuilder_ == null) {
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributeHandleValueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder addAttributeHandleValue(hla.rti1516_202X.fedpro.AttributeHandleValue value) {
      if (attributeHandleValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.add(value);
        onChanged();
      } else {
        attributeHandleValueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder addAttributeHandleValue(
        int index, hla.rti1516_202X.fedpro.AttributeHandleValue value) {
      if (attributeHandleValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.add(index, value);
        onChanged();
      } else {
        attributeHandleValueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder addAttributeHandleValue(
        hla.rti1516_202X.fedpro.AttributeHandleValue.Builder builderForValue) {
      if (attributeHandleValueBuilder_ == null) {
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.add(builderForValue.build());
        onChanged();
      } else {
        attributeHandleValueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder addAttributeHandleValue(
        int index, hla.rti1516_202X.fedpro.AttributeHandleValue.Builder builderForValue) {
      if (attributeHandleValueBuilder_ == null) {
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributeHandleValueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder addAllAttributeHandleValue(
        java.lang.Iterable<? extends hla.rti1516_202X.fedpro.AttributeHandleValue> values) {
      if (attributeHandleValueBuilder_ == null) {
        ensureAttributeHandleValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributeHandleValue_);
        onChanged();
      } else {
        attributeHandleValueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder clearAttributeHandleValue() {
      if (attributeHandleValueBuilder_ == null) {
        attributeHandleValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        attributeHandleValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public Builder removeAttributeHandleValue(int index) {
      if (attributeHandleValueBuilder_ == null) {
        ensureAttributeHandleValueIsMutable();
        attributeHandleValue_.remove(index);
        onChanged();
      } else {
        attributeHandleValueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValue.Builder getAttributeHandleValueBuilder(
        int index) {
      return getAttributeHandleValueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder getAttributeHandleValueOrBuilder(
        int index) {
      if (attributeHandleValueBuilder_ == null) {
        return attributeHandleValue_.get(index);  } else {
        return attributeHandleValueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public java.util.List<? extends hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder> 
         getAttributeHandleValueOrBuilderList() {
      if (attributeHandleValueBuilder_ != null) {
        return attributeHandleValueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributeHandleValue_);
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValue.Builder addAttributeHandleValueBuilder() {
      return getAttributeHandleValueFieldBuilder().addBuilder(
          hla.rti1516_202X.fedpro.AttributeHandleValue.getDefaultInstance());
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValue.Builder addAttributeHandleValueBuilder(
        int index) {
      return getAttributeHandleValueFieldBuilder().addBuilder(
          index, hla.rti1516_202X.fedpro.AttributeHandleValue.getDefaultInstance());
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
     */
    public java.util.List<hla.rti1516_202X.fedpro.AttributeHandleValue.Builder> 
         getAttributeHandleValueBuilderList() {
      return getAttributeHandleValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        hla.rti1516_202X.fedpro.AttributeHandleValue, hla.rti1516_202X.fedpro.AttributeHandleValue.Builder, hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder> 
        getAttributeHandleValueFieldBuilder() {
      if (attributeHandleValueBuilder_ == null) {
        attributeHandleValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            hla.rti1516_202X.fedpro.AttributeHandleValue, hla.rti1516_202X.fedpro.AttributeHandleValue.Builder, hla.rti1516_202X.fedpro.AttributeHandleValueOrBuilder>(
                attributeHandleValue_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        attributeHandleValue_ = null;
      }
      return attributeHandleValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti1516_202X.fedpro.AttributeHandleValueMap)
  }

  // @@protoc_insertion_point(class_scope:rti1516_202X.fedpro.AttributeHandleValueMap)
  private static final hla.rti1516_202X.fedpro.AttributeHandleValueMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hla.rti1516_202X.fedpro.AttributeHandleValueMap();
  }

  public static hla.rti1516_202X.fedpro.AttributeHandleValueMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttributeHandleValueMap>
      PARSER = new com.google.protobuf.AbstractParser<AttributeHandleValueMap>() {
    @java.lang.Override
    public AttributeHandleValueMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AttributeHandleValueMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttributeHandleValueMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hla.rti1516_202X.fedpro.AttributeHandleValueMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

