// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.fedpro;

public interface AttributeHandleValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.AttributeHandleValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_202X.fedpro.AttributeHandle attributeHandle = 1;</code>
   * @return Whether the attributeHandle field is set.
   */
  boolean hasAttributeHandle();
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandle attributeHandle = 1;</code>
   * @return The attributeHandle.
   */
  hla.rti1516_202X.fedpro.AttributeHandle getAttributeHandle();
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandle attributeHandle = 1;</code>
   */
  hla.rti1516_202X.fedpro.AttributeHandleOrBuilder getAttributeHandleOrBuilder();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
