// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.fedpro;

public interface ConnectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.ConnectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_202X.fedpro.ConfigurationResult configurationResult = 1;</code>
   * @return Whether the configurationResult field is set.
   */
  boolean hasConfigurationResult();
  /**
   * <code>.rti1516_202X.fedpro.ConfigurationResult configurationResult = 1;</code>
   * @return The configurationResult.
   */
  hla.rti1516_202X.fedpro.ConfigurationResult getConfigurationResult();
  /**
   * <code>.rti1516_202X.fedpro.ConfigurationResult configurationResult = 1;</code>
   */
  hla.rti1516_202X.fedpro.ConfigurationResultOrBuilder getConfigurationResultOrBuilder();
}
