// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.fedpro;

/**
 * <pre>
 * Set of DimensionHandle elements.
 * The set shall not contain duplicate elements.
 * </pre>
 *
 * Protobuf type {@code rti1516_202X.fedpro.DimensionHandleSet}
 */
public final class DimensionHandleSet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti1516_202X.fedpro.DimensionHandleSet)
    DimensionHandleSetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DimensionHandleSet.newBuilder() to construct.
  private DimensionHandleSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DimensionHandleSet() {
    dimensionHandle_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DimensionHandleSet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_DimensionHandleSet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_DimensionHandleSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hla.rti1516_202X.fedpro.DimensionHandleSet.class, hla.rti1516_202X.fedpro.DimensionHandleSet.Builder.class);
  }

  public static final int DIMENSIONHANDLE_FIELD_NUMBER = 1;
  private java.util.List<hla.rti1516_202X.fedpro.DimensionHandle> dimensionHandle_;
  /**
   * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
   */
  @java.lang.Override
  public java.util.List<hla.rti1516_202X.fedpro.DimensionHandle> getDimensionHandleList() {
    return dimensionHandle_;
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends hla.rti1516_202X.fedpro.DimensionHandleOrBuilder> 
      getDimensionHandleOrBuilderList() {
    return dimensionHandle_;
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
   */
  @java.lang.Override
  public int getDimensionHandleCount() {
    return dimensionHandle_.size();
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.DimensionHandle getDimensionHandle(int index) {
    return dimensionHandle_.get(index);
  }
  /**
   * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.DimensionHandleOrBuilder getDimensionHandleOrBuilder(
      int index) {
    return dimensionHandle_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dimensionHandle_.size(); i++) {
      output.writeMessage(1, dimensionHandle_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dimensionHandle_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dimensionHandle_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hla.rti1516_202X.fedpro.DimensionHandleSet)) {
      return super.equals(obj);
    }
    hla.rti1516_202X.fedpro.DimensionHandleSet other = (hla.rti1516_202X.fedpro.DimensionHandleSet) obj;

    if (!getDimensionHandleList()
        .equals(other.getDimensionHandleList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDimensionHandleCount() > 0) {
      hash = (37 * hash) + DIMENSIONHANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getDimensionHandleList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.DimensionHandleSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hla.rti1516_202X.fedpro.DimensionHandleSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Set of DimensionHandle elements.
   * The set shall not contain duplicate elements.
   * </pre>
   *
   * Protobuf type {@code rti1516_202X.fedpro.DimensionHandleSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti1516_202X.fedpro.DimensionHandleSet)
      hla.rti1516_202X.fedpro.DimensionHandleSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_DimensionHandleSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_DimensionHandleSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hla.rti1516_202X.fedpro.DimensionHandleSet.class, hla.rti1516_202X.fedpro.DimensionHandleSet.Builder.class);
    }

    // Construct using hla.rti1516_202X.fedpro.DimensionHandleSet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dimensionHandleBuilder_ == null) {
        dimensionHandle_ = java.util.Collections.emptyList();
      } else {
        dimensionHandle_ = null;
        dimensionHandleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_DimensionHandleSet_descriptor;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.DimensionHandleSet getDefaultInstanceForType() {
      return hla.rti1516_202X.fedpro.DimensionHandleSet.getDefaultInstance();
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.DimensionHandleSet build() {
      hla.rti1516_202X.fedpro.DimensionHandleSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.DimensionHandleSet buildPartial() {
      hla.rti1516_202X.fedpro.DimensionHandleSet result = new hla.rti1516_202X.fedpro.DimensionHandleSet(this);
      int from_bitField0_ = bitField0_;
      if (dimensionHandleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          dimensionHandle_ = java.util.Collections.unmodifiableList(dimensionHandle_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dimensionHandle_ = dimensionHandle_;
      } else {
        result.dimensionHandle_ = dimensionHandleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hla.rti1516_202X.fedpro.DimensionHandleSet) {
        return mergeFrom((hla.rti1516_202X.fedpro.DimensionHandleSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hla.rti1516_202X.fedpro.DimensionHandleSet other) {
      if (other == hla.rti1516_202X.fedpro.DimensionHandleSet.getDefaultInstance()) return this;
      if (dimensionHandleBuilder_ == null) {
        if (!other.dimensionHandle_.isEmpty()) {
          if (dimensionHandle_.isEmpty()) {
            dimensionHandle_ = other.dimensionHandle_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDimensionHandleIsMutable();
            dimensionHandle_.addAll(other.dimensionHandle_);
          }
          onChanged();
        }
      } else {
        if (!other.dimensionHandle_.isEmpty()) {
          if (dimensionHandleBuilder_.isEmpty()) {
            dimensionHandleBuilder_.dispose();
            dimensionHandleBuilder_ = null;
            dimensionHandle_ = other.dimensionHandle_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dimensionHandleBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDimensionHandleFieldBuilder() : null;
          } else {
            dimensionHandleBuilder_.addAllMessages(other.dimensionHandle_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hla.rti1516_202X.fedpro.DimensionHandle m =
                  input.readMessage(
                      hla.rti1516_202X.fedpro.DimensionHandle.parser(),
                      extensionRegistry);
              if (dimensionHandleBuilder_ == null) {
                ensureDimensionHandleIsMutable();
                dimensionHandle_.add(m);
              } else {
                dimensionHandleBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<hla.rti1516_202X.fedpro.DimensionHandle> dimensionHandle_ =
      java.util.Collections.emptyList();
    private void ensureDimensionHandleIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dimensionHandle_ = new java.util.ArrayList<hla.rti1516_202X.fedpro.DimensionHandle>(dimensionHandle_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        hla.rti1516_202X.fedpro.DimensionHandle, hla.rti1516_202X.fedpro.DimensionHandle.Builder, hla.rti1516_202X.fedpro.DimensionHandleOrBuilder> dimensionHandleBuilder_;

    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public java.util.List<hla.rti1516_202X.fedpro.DimensionHandle> getDimensionHandleList() {
      if (dimensionHandleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dimensionHandle_);
      } else {
        return dimensionHandleBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public int getDimensionHandleCount() {
      if (dimensionHandleBuilder_ == null) {
        return dimensionHandle_.size();
      } else {
        return dimensionHandleBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public hla.rti1516_202X.fedpro.DimensionHandle getDimensionHandle(int index) {
      if (dimensionHandleBuilder_ == null) {
        return dimensionHandle_.get(index);
      } else {
        return dimensionHandleBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder setDimensionHandle(
        int index, hla.rti1516_202X.fedpro.DimensionHandle value) {
      if (dimensionHandleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimensionHandleIsMutable();
        dimensionHandle_.set(index, value);
        onChanged();
      } else {
        dimensionHandleBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder setDimensionHandle(
        int index, hla.rti1516_202X.fedpro.DimensionHandle.Builder builderForValue) {
      if (dimensionHandleBuilder_ == null) {
        ensureDimensionHandleIsMutable();
        dimensionHandle_.set(index, builderForValue.build());
        onChanged();
      } else {
        dimensionHandleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder addDimensionHandle(hla.rti1516_202X.fedpro.DimensionHandle value) {
      if (dimensionHandleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimensionHandleIsMutable();
        dimensionHandle_.add(value);
        onChanged();
      } else {
        dimensionHandleBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder addDimensionHandle(
        int index, hla.rti1516_202X.fedpro.DimensionHandle value) {
      if (dimensionHandleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimensionHandleIsMutable();
        dimensionHandle_.add(index, value);
        onChanged();
      } else {
        dimensionHandleBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder addDimensionHandle(
        hla.rti1516_202X.fedpro.DimensionHandle.Builder builderForValue) {
      if (dimensionHandleBuilder_ == null) {
        ensureDimensionHandleIsMutable();
        dimensionHandle_.add(builderForValue.build());
        onChanged();
      } else {
        dimensionHandleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder addDimensionHandle(
        int index, hla.rti1516_202X.fedpro.DimensionHandle.Builder builderForValue) {
      if (dimensionHandleBuilder_ == null) {
        ensureDimensionHandleIsMutable();
        dimensionHandle_.add(index, builderForValue.build());
        onChanged();
      } else {
        dimensionHandleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder addAllDimensionHandle(
        java.lang.Iterable<? extends hla.rti1516_202X.fedpro.DimensionHandle> values) {
      if (dimensionHandleBuilder_ == null) {
        ensureDimensionHandleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dimensionHandle_);
        onChanged();
      } else {
        dimensionHandleBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder clearDimensionHandle() {
      if (dimensionHandleBuilder_ == null) {
        dimensionHandle_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dimensionHandleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public Builder removeDimensionHandle(int index) {
      if (dimensionHandleBuilder_ == null) {
        ensureDimensionHandleIsMutable();
        dimensionHandle_.remove(index);
        onChanged();
      } else {
        dimensionHandleBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public hla.rti1516_202X.fedpro.DimensionHandle.Builder getDimensionHandleBuilder(
        int index) {
      return getDimensionHandleFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public hla.rti1516_202X.fedpro.DimensionHandleOrBuilder getDimensionHandleOrBuilder(
        int index) {
      if (dimensionHandleBuilder_ == null) {
        return dimensionHandle_.get(index);  } else {
        return dimensionHandleBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public java.util.List<? extends hla.rti1516_202X.fedpro.DimensionHandleOrBuilder> 
         getDimensionHandleOrBuilderList() {
      if (dimensionHandleBuilder_ != null) {
        return dimensionHandleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dimensionHandle_);
      }
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public hla.rti1516_202X.fedpro.DimensionHandle.Builder addDimensionHandleBuilder() {
      return getDimensionHandleFieldBuilder().addBuilder(
          hla.rti1516_202X.fedpro.DimensionHandle.getDefaultInstance());
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public hla.rti1516_202X.fedpro.DimensionHandle.Builder addDimensionHandleBuilder(
        int index) {
      return getDimensionHandleFieldBuilder().addBuilder(
          index, hla.rti1516_202X.fedpro.DimensionHandle.getDefaultInstance());
    }
    /**
     * <code>repeated .rti1516_202X.fedpro.DimensionHandle dimensionHandle = 1;</code>
     */
    public java.util.List<hla.rti1516_202X.fedpro.DimensionHandle.Builder> 
         getDimensionHandleBuilderList() {
      return getDimensionHandleFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        hla.rti1516_202X.fedpro.DimensionHandle, hla.rti1516_202X.fedpro.DimensionHandle.Builder, hla.rti1516_202X.fedpro.DimensionHandleOrBuilder> 
        getDimensionHandleFieldBuilder() {
      if (dimensionHandleBuilder_ == null) {
        dimensionHandleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            hla.rti1516_202X.fedpro.DimensionHandle, hla.rti1516_202X.fedpro.DimensionHandle.Builder, hla.rti1516_202X.fedpro.DimensionHandleOrBuilder>(
                dimensionHandle_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        dimensionHandle_ = null;
      }
      return dimensionHandleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti1516_202X.fedpro.DimensionHandleSet)
  }

  // @@protoc_insertion_point(class_scope:rti1516_202X.fedpro.DimensionHandleSet)
  private static final hla.rti1516_202X.fedpro.DimensionHandleSet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hla.rti1516_202X.fedpro.DimensionHandleSet();
  }

  public static hla.rti1516_202X.fedpro.DimensionHandleSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DimensionHandleSet>
      PARSER = new com.google.protobuf.AbstractParser<DimensionHandleSet>() {
    @java.lang.Override
    public DimensionHandleSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DimensionHandleSet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DimensionHandleSet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hla.rti1516_202X.fedpro.DimensionHandleSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

