// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.fedpro;

public interface GetAttributeHandleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.GetAttributeHandleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_202X.fedpro.AttributeHandle result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandle result = 1;</code>
   * @return The result.
   */
  hla.rti1516_202X.fedpro.AttributeHandle getResult();
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandle result = 1;</code>
   */
  hla.rti1516_202X.fedpro.AttributeHandleOrBuilder getResultOrBuilder();
}
