// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.fedpro;

public interface GetNonRegulatedGrantSwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.GetNonRegulatedGrantSwitchRequest)
    com.google.protobuf.MessageOrBuilder {
}
