// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.fedpro;

public interface InteractionClassHandleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.InteractionClassHandle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
