// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTIambassador.proto

package hla.rti1516_202X.fedpro;

public interface IsAttributeOwnedByFederateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.IsAttributeOwnedByFederateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();
}
