// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FederateAmbassador.proto

package hla.rti1516_202X.fedpro;

/**
 * Protobuf type {@code rti1516_202X.fedpro.ReflectAttributeValuesWithTime}
 */
public final class ReflectAttributeValuesWithTime extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti1516_202X.fedpro.ReflectAttributeValuesWithTime)
    ReflectAttributeValuesWithTimeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReflectAttributeValuesWithTime.newBuilder() to construct.
  private ReflectAttributeValuesWithTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReflectAttributeValuesWithTime() {
    userSuppliedTag_ = com.google.protobuf.ByteString.EMPTY;
    sentOrderType_ = 0;
    receivedOrderType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReflectAttributeValuesWithTime();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hla.rti1516_202X.fedpro.FederateAmbassador.internal_static_rti1516_202X_fedpro_ReflectAttributeValuesWithTime_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hla.rti1516_202X.fedpro.FederateAmbassador.internal_static_rti1516_202X_fedpro_ReflectAttributeValuesWithTime_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.class, hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.Builder.class);
  }

  public static final int OBJECTINSTANCE_FIELD_NUMBER = 1;
  private hla.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance_;
  /**
   * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   * @return Whether the objectInstance field is set.
   */
  @java.lang.Override
  public boolean hasObjectInstance() {
    return objectInstance_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   * @return The objectInstance.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.ObjectInstanceHandle getObjectInstance() {
    return objectInstance_ == null ? hla.rti1516_202X.fedpro.ObjectInstanceHandle.getDefaultInstance() : objectInstance_;
  }
  /**
   * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.ObjectInstanceHandleOrBuilder getObjectInstanceOrBuilder() {
    return getObjectInstance();
  }

  public static final int ATTRIBUTEVALUES_FIELD_NUMBER = 2;
  private hla.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues_;
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
   * @return Whether the attributeValues field is set.
   */
  @java.lang.Override
  public boolean hasAttributeValues() {
    return attributeValues_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
   * @return The attributeValues.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.AttributeHandleValueMap getAttributeValues() {
    return attributeValues_ == null ? hla.rti1516_202X.fedpro.AttributeHandleValueMap.getDefaultInstance() : attributeValues_;
  }
  /**
   * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.AttributeHandleValueMapOrBuilder getAttributeValuesOrBuilder() {
    return getAttributeValues();
  }

  public static final int USERSUPPLIEDTAG_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString userSuppliedTag_;
  /**
   * <code>bytes userSuppliedTag = 3;</code>
   * @return The userSuppliedTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getUserSuppliedTag() {
    return userSuppliedTag_;
  }

  public static final int TRANSPORTATIONTYPE_FIELD_NUMBER = 4;
  private hla.rti1516_202X.fedpro.TransportationTypeHandle transportationType_;
  /**
   * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
   * @return Whether the transportationType field is set.
   */
  @java.lang.Override
  public boolean hasTransportationType() {
    return transportationType_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
   * @return The transportationType.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.TransportationTypeHandle getTransportationType() {
    return transportationType_ == null ? hla.rti1516_202X.fedpro.TransportationTypeHandle.getDefaultInstance() : transportationType_;
  }
  /**
   * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.TransportationTypeHandleOrBuilder getTransportationTypeOrBuilder() {
    return getTransportationType();
  }

  public static final int PRODUCINGFEDERATE_FIELD_NUMBER = 5;
  private hla.rti1516_202X.fedpro.FederateHandle producingFederate_;
  /**
   * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
   * @return Whether the producingFederate field is set.
   */
  @java.lang.Override
  public boolean hasProducingFederate() {
    return producingFederate_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
   * @return The producingFederate.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.FederateHandle getProducingFederate() {
    return producingFederate_ == null ? hla.rti1516_202X.fedpro.FederateHandle.getDefaultInstance() : producingFederate_;
  }
  /**
   * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.FederateHandleOrBuilder getProducingFederateOrBuilder() {
    return getProducingFederate();
  }

  public static final int OPTIONALSENTREGIONS_FIELD_NUMBER = 6;
  private hla.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions_;
  /**
   * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
   * @return Whether the optionalSentRegions field is set.
   */
  @java.lang.Override
  public boolean hasOptionalSentRegions() {
    return optionalSentRegions_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
   * @return The optionalSentRegions.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.ConveyedRegionSet getOptionalSentRegions() {
    return optionalSentRegions_ == null ? hla.rti1516_202X.fedpro.ConveyedRegionSet.getDefaultInstance() : optionalSentRegions_;
  }
  /**
   * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.ConveyedRegionSetOrBuilder getOptionalSentRegionsOrBuilder() {
    return getOptionalSentRegions();
  }

  public static final int TIME_FIELD_NUMBER = 7;
  private hla.rti1516_202X.fedpro.LogicalTime time_;
  /**
   * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
   * @return Whether the time field is set.
   */
  @java.lang.Override
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
   * @return The time.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.LogicalTime getTime() {
    return time_ == null ? hla.rti1516_202X.fedpro.LogicalTime.getDefaultInstance() : time_;
  }
  /**
   * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.LogicalTimeOrBuilder getTimeOrBuilder() {
    return getTime();
  }

  public static final int SENTORDERTYPE_FIELD_NUMBER = 8;
  private int sentOrderType_;
  /**
   * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
   * @return The enum numeric value on the wire for sentOrderType.
   */
  @java.lang.Override public int getSentOrderTypeValue() {
    return sentOrderType_;
  }
  /**
   * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
   * @return The sentOrderType.
   */
  @java.lang.Override public hla.rti1516_202X.fedpro.OrderType getSentOrderType() {
    @SuppressWarnings("deprecation")
    hla.rti1516_202X.fedpro.OrderType result = hla.rti1516_202X.fedpro.OrderType.valueOf(sentOrderType_);
    return result == null ? hla.rti1516_202X.fedpro.OrderType.UNRECOGNIZED : result;
  }

  public static final int RECEIVEDORDERTYPE_FIELD_NUMBER = 9;
  private int receivedOrderType_;
  /**
   * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
   * @return The enum numeric value on the wire for receivedOrderType.
   */
  @java.lang.Override public int getReceivedOrderTypeValue() {
    return receivedOrderType_;
  }
  /**
   * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
   * @return The receivedOrderType.
   */
  @java.lang.Override public hla.rti1516_202X.fedpro.OrderType getReceivedOrderType() {
    @SuppressWarnings("deprecation")
    hla.rti1516_202X.fedpro.OrderType result = hla.rti1516_202X.fedpro.OrderType.valueOf(receivedOrderType_);
    return result == null ? hla.rti1516_202X.fedpro.OrderType.UNRECOGNIZED : result;
  }

  public static final int OPTIONALRETRACTION_FIELD_NUMBER = 10;
  private hla.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction_;
  /**
   * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
   * @return Whether the optionalRetraction field is set.
   */
  @java.lang.Override
  public boolean hasOptionalRetraction() {
    return optionalRetraction_ != null;
  }
  /**
   * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
   * @return The optionalRetraction.
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.MessageRetractionHandle getOptionalRetraction() {
    return optionalRetraction_ == null ? hla.rti1516_202X.fedpro.MessageRetractionHandle.getDefaultInstance() : optionalRetraction_;
  }
  /**
   * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
   */
  @java.lang.Override
  public hla.rti1516_202X.fedpro.MessageRetractionHandleOrBuilder getOptionalRetractionOrBuilder() {
    return getOptionalRetraction();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (objectInstance_ != null) {
      output.writeMessage(1, getObjectInstance());
    }
    if (attributeValues_ != null) {
      output.writeMessage(2, getAttributeValues());
    }
    if (!userSuppliedTag_.isEmpty()) {
      output.writeBytes(3, userSuppliedTag_);
    }
    if (transportationType_ != null) {
      output.writeMessage(4, getTransportationType());
    }
    if (producingFederate_ != null) {
      output.writeMessage(5, getProducingFederate());
    }
    if (optionalSentRegions_ != null) {
      output.writeMessage(6, getOptionalSentRegions());
    }
    if (time_ != null) {
      output.writeMessage(7, getTime());
    }
    if (sentOrderType_ != hla.rti1516_202X.fedpro.OrderType.RECEIVE.getNumber()) {
      output.writeEnum(8, sentOrderType_);
    }
    if (receivedOrderType_ != hla.rti1516_202X.fedpro.OrderType.RECEIVE.getNumber()) {
      output.writeEnum(9, receivedOrderType_);
    }
    if (optionalRetraction_ != null) {
      output.writeMessage(10, getOptionalRetraction());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (objectInstance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getObjectInstance());
    }
    if (attributeValues_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAttributeValues());
    }
    if (!userSuppliedTag_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, userSuppliedTag_);
    }
    if (transportationType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTransportationType());
    }
    if (producingFederate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getProducingFederate());
    }
    if (optionalSentRegions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getOptionalSentRegions());
    }
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTime());
    }
    if (sentOrderType_ != hla.rti1516_202X.fedpro.OrderType.RECEIVE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, sentOrderType_);
    }
    if (receivedOrderType_ != hla.rti1516_202X.fedpro.OrderType.RECEIVE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, receivedOrderType_);
    }
    if (optionalRetraction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getOptionalRetraction());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime)) {
      return super.equals(obj);
    }
    hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime other = (hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime) obj;

    if (hasObjectInstance() != other.hasObjectInstance()) return false;
    if (hasObjectInstance()) {
      if (!getObjectInstance()
          .equals(other.getObjectInstance())) return false;
    }
    if (hasAttributeValues() != other.hasAttributeValues()) return false;
    if (hasAttributeValues()) {
      if (!getAttributeValues()
          .equals(other.getAttributeValues())) return false;
    }
    if (!getUserSuppliedTag()
        .equals(other.getUserSuppliedTag())) return false;
    if (hasTransportationType() != other.hasTransportationType()) return false;
    if (hasTransportationType()) {
      if (!getTransportationType()
          .equals(other.getTransportationType())) return false;
    }
    if (hasProducingFederate() != other.hasProducingFederate()) return false;
    if (hasProducingFederate()) {
      if (!getProducingFederate()
          .equals(other.getProducingFederate())) return false;
    }
    if (hasOptionalSentRegions() != other.hasOptionalSentRegions()) return false;
    if (hasOptionalSentRegions()) {
      if (!getOptionalSentRegions()
          .equals(other.getOptionalSentRegions())) return false;
    }
    if (hasTime() != other.hasTime()) return false;
    if (hasTime()) {
      if (!getTime()
          .equals(other.getTime())) return false;
    }
    if (sentOrderType_ != other.sentOrderType_) return false;
    if (receivedOrderType_ != other.receivedOrderType_) return false;
    if (hasOptionalRetraction() != other.hasOptionalRetraction()) return false;
    if (hasOptionalRetraction()) {
      if (!getOptionalRetraction()
          .equals(other.getOptionalRetraction())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasObjectInstance()) {
      hash = (37 * hash) + OBJECTINSTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getObjectInstance().hashCode();
    }
    if (hasAttributeValues()) {
      hash = (37 * hash) + ATTRIBUTEVALUES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeValues().hashCode();
    }
    hash = (37 * hash) + USERSUPPLIEDTAG_FIELD_NUMBER;
    hash = (53 * hash) + getUserSuppliedTag().hashCode();
    if (hasTransportationType()) {
      hash = (37 * hash) + TRANSPORTATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTransportationType().hashCode();
    }
    if (hasProducingFederate()) {
      hash = (37 * hash) + PRODUCINGFEDERATE_FIELD_NUMBER;
      hash = (53 * hash) + getProducingFederate().hashCode();
    }
    if (hasOptionalSentRegions()) {
      hash = (37 * hash) + OPTIONALSENTREGIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionalSentRegions().hashCode();
    }
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (37 * hash) + SENTORDERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + sentOrderType_;
    hash = (37 * hash) + RECEIVEDORDERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + receivedOrderType_;
    if (hasOptionalRetraction()) {
      hash = (37 * hash) + OPTIONALRETRACTION_FIELD_NUMBER;
      hash = (53 * hash) + getOptionalRetraction().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti1516_202X.fedpro.ReflectAttributeValuesWithTime}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti1516_202X.fedpro.ReflectAttributeValuesWithTime)
      hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTimeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hla.rti1516_202X.fedpro.FederateAmbassador.internal_static_rti1516_202X_fedpro_ReflectAttributeValuesWithTime_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hla.rti1516_202X.fedpro.FederateAmbassador.internal_static_rti1516_202X_fedpro_ReflectAttributeValuesWithTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.class, hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.Builder.class);
    }

    // Construct using hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (objectInstanceBuilder_ == null) {
        objectInstance_ = null;
      } else {
        objectInstance_ = null;
        objectInstanceBuilder_ = null;
      }
      if (attributeValuesBuilder_ == null) {
        attributeValues_ = null;
      } else {
        attributeValues_ = null;
        attributeValuesBuilder_ = null;
      }
      userSuppliedTag_ = com.google.protobuf.ByteString.EMPTY;

      if (transportationTypeBuilder_ == null) {
        transportationType_ = null;
      } else {
        transportationType_ = null;
        transportationTypeBuilder_ = null;
      }
      if (producingFederateBuilder_ == null) {
        producingFederate_ = null;
      } else {
        producingFederate_ = null;
        producingFederateBuilder_ = null;
      }
      if (optionalSentRegionsBuilder_ == null) {
        optionalSentRegions_ = null;
      } else {
        optionalSentRegions_ = null;
        optionalSentRegionsBuilder_ = null;
      }
      if (timeBuilder_ == null) {
        time_ = null;
      } else {
        time_ = null;
        timeBuilder_ = null;
      }
      sentOrderType_ = 0;

      receivedOrderType_ = 0;

      if (optionalRetractionBuilder_ == null) {
        optionalRetraction_ = null;
      } else {
        optionalRetraction_ = null;
        optionalRetractionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hla.rti1516_202X.fedpro.FederateAmbassador.internal_static_rti1516_202X_fedpro_ReflectAttributeValuesWithTime_descriptor;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime getDefaultInstanceForType() {
      return hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.getDefaultInstance();
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime build() {
      hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime buildPartial() {
      hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime result = new hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime(this);
      if (objectInstanceBuilder_ == null) {
        result.objectInstance_ = objectInstance_;
      } else {
        result.objectInstance_ = objectInstanceBuilder_.build();
      }
      if (attributeValuesBuilder_ == null) {
        result.attributeValues_ = attributeValues_;
      } else {
        result.attributeValues_ = attributeValuesBuilder_.build();
      }
      result.userSuppliedTag_ = userSuppliedTag_;
      if (transportationTypeBuilder_ == null) {
        result.transportationType_ = transportationType_;
      } else {
        result.transportationType_ = transportationTypeBuilder_.build();
      }
      if (producingFederateBuilder_ == null) {
        result.producingFederate_ = producingFederate_;
      } else {
        result.producingFederate_ = producingFederateBuilder_.build();
      }
      if (optionalSentRegionsBuilder_ == null) {
        result.optionalSentRegions_ = optionalSentRegions_;
      } else {
        result.optionalSentRegions_ = optionalSentRegionsBuilder_.build();
      }
      if (timeBuilder_ == null) {
        result.time_ = time_;
      } else {
        result.time_ = timeBuilder_.build();
      }
      result.sentOrderType_ = sentOrderType_;
      result.receivedOrderType_ = receivedOrderType_;
      if (optionalRetractionBuilder_ == null) {
        result.optionalRetraction_ = optionalRetraction_;
      } else {
        result.optionalRetraction_ = optionalRetractionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime) {
        return mergeFrom((hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime other) {
      if (other == hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime.getDefaultInstance()) return this;
      if (other.hasObjectInstance()) {
        mergeObjectInstance(other.getObjectInstance());
      }
      if (other.hasAttributeValues()) {
        mergeAttributeValues(other.getAttributeValues());
      }
      if (other.getUserSuppliedTag() != com.google.protobuf.ByteString.EMPTY) {
        setUserSuppliedTag(other.getUserSuppliedTag());
      }
      if (other.hasTransportationType()) {
        mergeTransportationType(other.getTransportationType());
      }
      if (other.hasProducingFederate()) {
        mergeProducingFederate(other.getProducingFederate());
      }
      if (other.hasOptionalSentRegions()) {
        mergeOptionalSentRegions(other.getOptionalSentRegions());
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (other.sentOrderType_ != 0) {
        setSentOrderTypeValue(other.getSentOrderTypeValue());
      }
      if (other.receivedOrderType_ != 0) {
        setReceivedOrderTypeValue(other.getReceivedOrderTypeValue());
      }
      if (other.hasOptionalRetraction()) {
        mergeOptionalRetraction(other.getOptionalRetraction());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getObjectInstanceFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAttributeValuesFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              userSuppliedTag_ = input.readBytes();

              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getTransportationTypeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getProducingFederateFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getOptionalSentRegionsFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 58
            case 64: {
              sentOrderType_ = input.readEnum();

              break;
            } // case 64
            case 72: {
              receivedOrderType_ = input.readEnum();

              break;
            } // case 72
            case 82: {
              input.readMessage(
                  getOptionalRetractionFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private hla.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.ObjectInstanceHandle, hla.rti1516_202X.fedpro.ObjectInstanceHandle.Builder, hla.rti1516_202X.fedpro.ObjectInstanceHandleOrBuilder> objectInstanceBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     * @return Whether the objectInstance field is set.
     */
    public boolean hasObjectInstance() {
      return objectInstanceBuilder_ != null || objectInstance_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     * @return The objectInstance.
     */
    public hla.rti1516_202X.fedpro.ObjectInstanceHandle getObjectInstance() {
      if (objectInstanceBuilder_ == null) {
        return objectInstance_ == null ? hla.rti1516_202X.fedpro.ObjectInstanceHandle.getDefaultInstance() : objectInstance_;
      } else {
        return objectInstanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    public Builder setObjectInstance(hla.rti1516_202X.fedpro.ObjectInstanceHandle value) {
      if (objectInstanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        objectInstance_ = value;
        onChanged();
      } else {
        objectInstanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    public Builder setObjectInstance(
        hla.rti1516_202X.fedpro.ObjectInstanceHandle.Builder builderForValue) {
      if (objectInstanceBuilder_ == null) {
        objectInstance_ = builderForValue.build();
        onChanged();
      } else {
        objectInstanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    public Builder mergeObjectInstance(hla.rti1516_202X.fedpro.ObjectInstanceHandle value) {
      if (objectInstanceBuilder_ == null) {
        if (objectInstance_ != null) {
          objectInstance_ =
            hla.rti1516_202X.fedpro.ObjectInstanceHandle.newBuilder(objectInstance_).mergeFrom(value).buildPartial();
        } else {
          objectInstance_ = value;
        }
        onChanged();
      } else {
        objectInstanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    public Builder clearObjectInstance() {
      if (objectInstanceBuilder_ == null) {
        objectInstance_ = null;
        onChanged();
      } else {
        objectInstance_ = null;
        objectInstanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    public hla.rti1516_202X.fedpro.ObjectInstanceHandle.Builder getObjectInstanceBuilder() {
      
      onChanged();
      return getObjectInstanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    public hla.rti1516_202X.fedpro.ObjectInstanceHandleOrBuilder getObjectInstanceOrBuilder() {
      if (objectInstanceBuilder_ != null) {
        return objectInstanceBuilder_.getMessageOrBuilder();
      } else {
        return objectInstance_ == null ?
            hla.rti1516_202X.fedpro.ObjectInstanceHandle.getDefaultInstance() : objectInstance_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.ObjectInstanceHandle, hla.rti1516_202X.fedpro.ObjectInstanceHandle.Builder, hla.rti1516_202X.fedpro.ObjectInstanceHandleOrBuilder> 
        getObjectInstanceFieldBuilder() {
      if (objectInstanceBuilder_ == null) {
        objectInstanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.ObjectInstanceHandle, hla.rti1516_202X.fedpro.ObjectInstanceHandle.Builder, hla.rti1516_202X.fedpro.ObjectInstanceHandleOrBuilder>(
                getObjectInstance(),
                getParentForChildren(),
                isClean());
        objectInstance_ = null;
      }
      return objectInstanceBuilder_;
    }

    private hla.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.AttributeHandleValueMap, hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder, hla.rti1516_202X.fedpro.AttributeHandleValueMapOrBuilder> attributeValuesBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     * @return Whether the attributeValues field is set.
     */
    public boolean hasAttributeValues() {
      return attributeValuesBuilder_ != null || attributeValues_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     * @return The attributeValues.
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValueMap getAttributeValues() {
      if (attributeValuesBuilder_ == null) {
        return attributeValues_ == null ? hla.rti1516_202X.fedpro.AttributeHandleValueMap.getDefaultInstance() : attributeValues_;
      } else {
        return attributeValuesBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    public Builder setAttributeValues(hla.rti1516_202X.fedpro.AttributeHandleValueMap value) {
      if (attributeValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attributeValues_ = value;
        onChanged();
      } else {
        attributeValuesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    public Builder setAttributeValues(
        hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder builderForValue) {
      if (attributeValuesBuilder_ == null) {
        attributeValues_ = builderForValue.build();
        onChanged();
      } else {
        attributeValuesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    public Builder mergeAttributeValues(hla.rti1516_202X.fedpro.AttributeHandleValueMap value) {
      if (attributeValuesBuilder_ == null) {
        if (attributeValues_ != null) {
          attributeValues_ =
            hla.rti1516_202X.fedpro.AttributeHandleValueMap.newBuilder(attributeValues_).mergeFrom(value).buildPartial();
        } else {
          attributeValues_ = value;
        }
        onChanged();
      } else {
        attributeValuesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    public Builder clearAttributeValues() {
      if (attributeValuesBuilder_ == null) {
        attributeValues_ = null;
        onChanged();
      } else {
        attributeValues_ = null;
        attributeValuesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder getAttributeValuesBuilder() {
      
      onChanged();
      return getAttributeValuesFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    public hla.rti1516_202X.fedpro.AttributeHandleValueMapOrBuilder getAttributeValuesOrBuilder() {
      if (attributeValuesBuilder_ != null) {
        return attributeValuesBuilder_.getMessageOrBuilder();
      } else {
        return attributeValues_ == null ?
            hla.rti1516_202X.fedpro.AttributeHandleValueMap.getDefaultInstance() : attributeValues_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.AttributeHandleValueMap attributeValues = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.AttributeHandleValueMap, hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder, hla.rti1516_202X.fedpro.AttributeHandleValueMapOrBuilder> 
        getAttributeValuesFieldBuilder() {
      if (attributeValuesBuilder_ == null) {
        attributeValuesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.AttributeHandleValueMap, hla.rti1516_202X.fedpro.AttributeHandleValueMap.Builder, hla.rti1516_202X.fedpro.AttributeHandleValueMapOrBuilder>(
                getAttributeValues(),
                getParentForChildren(),
                isClean());
        attributeValues_ = null;
      }
      return attributeValuesBuilder_;
    }

    private com.google.protobuf.ByteString userSuppliedTag_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes userSuppliedTag = 3;</code>
     * @return The userSuppliedTag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUserSuppliedTag() {
      return userSuppliedTag_;
    }
    /**
     * <code>bytes userSuppliedTag = 3;</code>
     * @param value The userSuppliedTag to set.
     * @return This builder for chaining.
     */
    public Builder setUserSuppliedTag(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userSuppliedTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes userSuppliedTag = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserSuppliedTag() {
      
      userSuppliedTag_ = getDefaultInstance().getUserSuppliedTag();
      onChanged();
      return this;
    }

    private hla.rti1516_202X.fedpro.TransportationTypeHandle transportationType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.TransportationTypeHandle, hla.rti1516_202X.fedpro.TransportationTypeHandle.Builder, hla.rti1516_202X.fedpro.TransportationTypeHandleOrBuilder> transportationTypeBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     * @return Whether the transportationType field is set.
     */
    public boolean hasTransportationType() {
      return transportationTypeBuilder_ != null || transportationType_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     * @return The transportationType.
     */
    public hla.rti1516_202X.fedpro.TransportationTypeHandle getTransportationType() {
      if (transportationTypeBuilder_ == null) {
        return transportationType_ == null ? hla.rti1516_202X.fedpro.TransportationTypeHandle.getDefaultInstance() : transportationType_;
      } else {
        return transportationTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    public Builder setTransportationType(hla.rti1516_202X.fedpro.TransportationTypeHandle value) {
      if (transportationTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transportationType_ = value;
        onChanged();
      } else {
        transportationTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    public Builder setTransportationType(
        hla.rti1516_202X.fedpro.TransportationTypeHandle.Builder builderForValue) {
      if (transportationTypeBuilder_ == null) {
        transportationType_ = builderForValue.build();
        onChanged();
      } else {
        transportationTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    public Builder mergeTransportationType(hla.rti1516_202X.fedpro.TransportationTypeHandle value) {
      if (transportationTypeBuilder_ == null) {
        if (transportationType_ != null) {
          transportationType_ =
            hla.rti1516_202X.fedpro.TransportationTypeHandle.newBuilder(transportationType_).mergeFrom(value).buildPartial();
        } else {
          transportationType_ = value;
        }
        onChanged();
      } else {
        transportationTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    public Builder clearTransportationType() {
      if (transportationTypeBuilder_ == null) {
        transportationType_ = null;
        onChanged();
      } else {
        transportationType_ = null;
        transportationTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    public hla.rti1516_202X.fedpro.TransportationTypeHandle.Builder getTransportationTypeBuilder() {
      
      onChanged();
      return getTransportationTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    public hla.rti1516_202X.fedpro.TransportationTypeHandleOrBuilder getTransportationTypeOrBuilder() {
      if (transportationTypeBuilder_ != null) {
        return transportationTypeBuilder_.getMessageOrBuilder();
      } else {
        return transportationType_ == null ?
            hla.rti1516_202X.fedpro.TransportationTypeHandle.getDefaultInstance() : transportationType_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.TransportationTypeHandle transportationType = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.TransportationTypeHandle, hla.rti1516_202X.fedpro.TransportationTypeHandle.Builder, hla.rti1516_202X.fedpro.TransportationTypeHandleOrBuilder> 
        getTransportationTypeFieldBuilder() {
      if (transportationTypeBuilder_ == null) {
        transportationTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.TransportationTypeHandle, hla.rti1516_202X.fedpro.TransportationTypeHandle.Builder, hla.rti1516_202X.fedpro.TransportationTypeHandleOrBuilder>(
                getTransportationType(),
                getParentForChildren(),
                isClean());
        transportationType_ = null;
      }
      return transportationTypeBuilder_;
    }

    private hla.rti1516_202X.fedpro.FederateHandle producingFederate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.FederateHandle, hla.rti1516_202X.fedpro.FederateHandle.Builder, hla.rti1516_202X.fedpro.FederateHandleOrBuilder> producingFederateBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     * @return Whether the producingFederate field is set.
     */
    public boolean hasProducingFederate() {
      return producingFederateBuilder_ != null || producingFederate_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     * @return The producingFederate.
     */
    public hla.rti1516_202X.fedpro.FederateHandle getProducingFederate() {
      if (producingFederateBuilder_ == null) {
        return producingFederate_ == null ? hla.rti1516_202X.fedpro.FederateHandle.getDefaultInstance() : producingFederate_;
      } else {
        return producingFederateBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    public Builder setProducingFederate(hla.rti1516_202X.fedpro.FederateHandle value) {
      if (producingFederateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        producingFederate_ = value;
        onChanged();
      } else {
        producingFederateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    public Builder setProducingFederate(
        hla.rti1516_202X.fedpro.FederateHandle.Builder builderForValue) {
      if (producingFederateBuilder_ == null) {
        producingFederate_ = builderForValue.build();
        onChanged();
      } else {
        producingFederateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    public Builder mergeProducingFederate(hla.rti1516_202X.fedpro.FederateHandle value) {
      if (producingFederateBuilder_ == null) {
        if (producingFederate_ != null) {
          producingFederate_ =
            hla.rti1516_202X.fedpro.FederateHandle.newBuilder(producingFederate_).mergeFrom(value).buildPartial();
        } else {
          producingFederate_ = value;
        }
        onChanged();
      } else {
        producingFederateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    public Builder clearProducingFederate() {
      if (producingFederateBuilder_ == null) {
        producingFederate_ = null;
        onChanged();
      } else {
        producingFederate_ = null;
        producingFederateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    public hla.rti1516_202X.fedpro.FederateHandle.Builder getProducingFederateBuilder() {
      
      onChanged();
      return getProducingFederateFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    public hla.rti1516_202X.fedpro.FederateHandleOrBuilder getProducingFederateOrBuilder() {
      if (producingFederateBuilder_ != null) {
        return producingFederateBuilder_.getMessageOrBuilder();
      } else {
        return producingFederate_ == null ?
            hla.rti1516_202X.fedpro.FederateHandle.getDefaultInstance() : producingFederate_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.FederateHandle producingFederate = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.FederateHandle, hla.rti1516_202X.fedpro.FederateHandle.Builder, hla.rti1516_202X.fedpro.FederateHandleOrBuilder> 
        getProducingFederateFieldBuilder() {
      if (producingFederateBuilder_ == null) {
        producingFederateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.FederateHandle, hla.rti1516_202X.fedpro.FederateHandle.Builder, hla.rti1516_202X.fedpro.FederateHandleOrBuilder>(
                getProducingFederate(),
                getParentForChildren(),
                isClean());
        producingFederate_ = null;
      }
      return producingFederateBuilder_;
    }

    private hla.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.ConveyedRegionSet, hla.rti1516_202X.fedpro.ConveyedRegionSet.Builder, hla.rti1516_202X.fedpro.ConveyedRegionSetOrBuilder> optionalSentRegionsBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     * @return Whether the optionalSentRegions field is set.
     */
    public boolean hasOptionalSentRegions() {
      return optionalSentRegionsBuilder_ != null || optionalSentRegions_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     * @return The optionalSentRegions.
     */
    public hla.rti1516_202X.fedpro.ConveyedRegionSet getOptionalSentRegions() {
      if (optionalSentRegionsBuilder_ == null) {
        return optionalSentRegions_ == null ? hla.rti1516_202X.fedpro.ConveyedRegionSet.getDefaultInstance() : optionalSentRegions_;
      } else {
        return optionalSentRegionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    public Builder setOptionalSentRegions(hla.rti1516_202X.fedpro.ConveyedRegionSet value) {
      if (optionalSentRegionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        optionalSentRegions_ = value;
        onChanged();
      } else {
        optionalSentRegionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    public Builder setOptionalSentRegions(
        hla.rti1516_202X.fedpro.ConveyedRegionSet.Builder builderForValue) {
      if (optionalSentRegionsBuilder_ == null) {
        optionalSentRegions_ = builderForValue.build();
        onChanged();
      } else {
        optionalSentRegionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    public Builder mergeOptionalSentRegions(hla.rti1516_202X.fedpro.ConveyedRegionSet value) {
      if (optionalSentRegionsBuilder_ == null) {
        if (optionalSentRegions_ != null) {
          optionalSentRegions_ =
            hla.rti1516_202X.fedpro.ConveyedRegionSet.newBuilder(optionalSentRegions_).mergeFrom(value).buildPartial();
        } else {
          optionalSentRegions_ = value;
        }
        onChanged();
      } else {
        optionalSentRegionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    public Builder clearOptionalSentRegions() {
      if (optionalSentRegionsBuilder_ == null) {
        optionalSentRegions_ = null;
        onChanged();
      } else {
        optionalSentRegions_ = null;
        optionalSentRegionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    public hla.rti1516_202X.fedpro.ConveyedRegionSet.Builder getOptionalSentRegionsBuilder() {
      
      onChanged();
      return getOptionalSentRegionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    public hla.rti1516_202X.fedpro.ConveyedRegionSetOrBuilder getOptionalSentRegionsOrBuilder() {
      if (optionalSentRegionsBuilder_ != null) {
        return optionalSentRegionsBuilder_.getMessageOrBuilder();
      } else {
        return optionalSentRegions_ == null ?
            hla.rti1516_202X.fedpro.ConveyedRegionSet.getDefaultInstance() : optionalSentRegions_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.ConveyedRegionSet optionalSentRegions = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.ConveyedRegionSet, hla.rti1516_202X.fedpro.ConveyedRegionSet.Builder, hla.rti1516_202X.fedpro.ConveyedRegionSetOrBuilder> 
        getOptionalSentRegionsFieldBuilder() {
      if (optionalSentRegionsBuilder_ == null) {
        optionalSentRegionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.ConveyedRegionSet, hla.rti1516_202X.fedpro.ConveyedRegionSet.Builder, hla.rti1516_202X.fedpro.ConveyedRegionSetOrBuilder>(
                getOptionalSentRegions(),
                getParentForChildren(),
                isClean());
        optionalSentRegions_ = null;
      }
      return optionalSentRegionsBuilder_;
    }

    private hla.rti1516_202X.fedpro.LogicalTime time_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.LogicalTime, hla.rti1516_202X.fedpro.LogicalTime.Builder, hla.rti1516_202X.fedpro.LogicalTimeOrBuilder> timeBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return timeBuilder_ != null || time_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     * @return The time.
     */
    public hla.rti1516_202X.fedpro.LogicalTime getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? hla.rti1516_202X.fedpro.LogicalTime.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    public Builder setTime(hla.rti1516_202X.fedpro.LogicalTime value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        timeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    public Builder setTime(
        hla.rti1516_202X.fedpro.LogicalTime.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    public Builder mergeTime(hla.rti1516_202X.fedpro.LogicalTime value) {
      if (timeBuilder_ == null) {
        if (time_ != null) {
          time_ =
            hla.rti1516_202X.fedpro.LogicalTime.newBuilder(time_).mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        timeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    public Builder clearTime() {
      if (timeBuilder_ == null) {
        time_ = null;
        onChanged();
      } else {
        time_ = null;
        timeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    public hla.rti1516_202X.fedpro.LogicalTime.Builder getTimeBuilder() {
      
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    public hla.rti1516_202X.fedpro.LogicalTimeOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            hla.rti1516_202X.fedpro.LogicalTime.getDefaultInstance() : time_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.LogicalTime time = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.LogicalTime, hla.rti1516_202X.fedpro.LogicalTime.Builder, hla.rti1516_202X.fedpro.LogicalTimeOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.LogicalTime, hla.rti1516_202X.fedpro.LogicalTime.Builder, hla.rti1516_202X.fedpro.LogicalTimeOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private int sentOrderType_ = 0;
    /**
     * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
     * @return The enum numeric value on the wire for sentOrderType.
     */
    @java.lang.Override public int getSentOrderTypeValue() {
      return sentOrderType_;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
     * @param value The enum numeric value on the wire for sentOrderType to set.
     * @return This builder for chaining.
     */
    public Builder setSentOrderTypeValue(int value) {
      
      sentOrderType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
     * @return The sentOrderType.
     */
    @java.lang.Override
    public hla.rti1516_202X.fedpro.OrderType getSentOrderType() {
      @SuppressWarnings("deprecation")
      hla.rti1516_202X.fedpro.OrderType result = hla.rti1516_202X.fedpro.OrderType.valueOf(sentOrderType_);
      return result == null ? hla.rti1516_202X.fedpro.OrderType.UNRECOGNIZED : result;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
     * @param value The sentOrderType to set.
     * @return This builder for chaining.
     */
    public Builder setSentOrderType(hla.rti1516_202X.fedpro.OrderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      sentOrderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType sentOrderType = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSentOrderType() {
      
      sentOrderType_ = 0;
      onChanged();
      return this;
    }

    private int receivedOrderType_ = 0;
    /**
     * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
     * @return The enum numeric value on the wire for receivedOrderType.
     */
    @java.lang.Override public int getReceivedOrderTypeValue() {
      return receivedOrderType_;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
     * @param value The enum numeric value on the wire for receivedOrderType to set.
     * @return This builder for chaining.
     */
    public Builder setReceivedOrderTypeValue(int value) {
      
      receivedOrderType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
     * @return The receivedOrderType.
     */
    @java.lang.Override
    public hla.rti1516_202X.fedpro.OrderType getReceivedOrderType() {
      @SuppressWarnings("deprecation")
      hla.rti1516_202X.fedpro.OrderType result = hla.rti1516_202X.fedpro.OrderType.valueOf(receivedOrderType_);
      return result == null ? hla.rti1516_202X.fedpro.OrderType.UNRECOGNIZED : result;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
     * @param value The receivedOrderType to set.
     * @return This builder for chaining.
     */
    public Builder setReceivedOrderType(hla.rti1516_202X.fedpro.OrderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      receivedOrderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.OrderType receivedOrderType = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceivedOrderType() {
      
      receivedOrderType_ = 0;
      onChanged();
      return this;
    }

    private hla.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.MessageRetractionHandle, hla.rti1516_202X.fedpro.MessageRetractionHandle.Builder, hla.rti1516_202X.fedpro.MessageRetractionHandleOrBuilder> optionalRetractionBuilder_;
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     * @return Whether the optionalRetraction field is set.
     */
    public boolean hasOptionalRetraction() {
      return optionalRetractionBuilder_ != null || optionalRetraction_ != null;
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     * @return The optionalRetraction.
     */
    public hla.rti1516_202X.fedpro.MessageRetractionHandle getOptionalRetraction() {
      if (optionalRetractionBuilder_ == null) {
        return optionalRetraction_ == null ? hla.rti1516_202X.fedpro.MessageRetractionHandle.getDefaultInstance() : optionalRetraction_;
      } else {
        return optionalRetractionBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    public Builder setOptionalRetraction(hla.rti1516_202X.fedpro.MessageRetractionHandle value) {
      if (optionalRetractionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        optionalRetraction_ = value;
        onChanged();
      } else {
        optionalRetractionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    public Builder setOptionalRetraction(
        hla.rti1516_202X.fedpro.MessageRetractionHandle.Builder builderForValue) {
      if (optionalRetractionBuilder_ == null) {
        optionalRetraction_ = builderForValue.build();
        onChanged();
      } else {
        optionalRetractionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    public Builder mergeOptionalRetraction(hla.rti1516_202X.fedpro.MessageRetractionHandle value) {
      if (optionalRetractionBuilder_ == null) {
        if (optionalRetraction_ != null) {
          optionalRetraction_ =
            hla.rti1516_202X.fedpro.MessageRetractionHandle.newBuilder(optionalRetraction_).mergeFrom(value).buildPartial();
        } else {
          optionalRetraction_ = value;
        }
        onChanged();
      } else {
        optionalRetractionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    public Builder clearOptionalRetraction() {
      if (optionalRetractionBuilder_ == null) {
        optionalRetraction_ = null;
        onChanged();
      } else {
        optionalRetraction_ = null;
        optionalRetractionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    public hla.rti1516_202X.fedpro.MessageRetractionHandle.Builder getOptionalRetractionBuilder() {
      
      onChanged();
      return getOptionalRetractionFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    public hla.rti1516_202X.fedpro.MessageRetractionHandleOrBuilder getOptionalRetractionOrBuilder() {
      if (optionalRetractionBuilder_ != null) {
        return optionalRetractionBuilder_.getMessageOrBuilder();
      } else {
        return optionalRetraction_ == null ?
            hla.rti1516_202X.fedpro.MessageRetractionHandle.getDefaultInstance() : optionalRetraction_;
      }
    }
    /**
     * <code>.rti1516_202X.fedpro.MessageRetractionHandle optionalRetraction = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hla.rti1516_202X.fedpro.MessageRetractionHandle, hla.rti1516_202X.fedpro.MessageRetractionHandle.Builder, hla.rti1516_202X.fedpro.MessageRetractionHandleOrBuilder> 
        getOptionalRetractionFieldBuilder() {
      if (optionalRetractionBuilder_ == null) {
        optionalRetractionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hla.rti1516_202X.fedpro.MessageRetractionHandle, hla.rti1516_202X.fedpro.MessageRetractionHandle.Builder, hla.rti1516_202X.fedpro.MessageRetractionHandleOrBuilder>(
                getOptionalRetraction(),
                getParentForChildren(),
                isClean());
        optionalRetraction_ = null;
      }
      return optionalRetractionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti1516_202X.fedpro.ReflectAttributeValuesWithTime)
  }

  // @@protoc_insertion_point(class_scope:rti1516_202X.fedpro.ReflectAttributeValuesWithTime)
  private static final hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime();
  }

  public static hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReflectAttributeValuesWithTime>
      PARSER = new com.google.protobuf.AbstractParser<ReflectAttributeValuesWithTime>() {
    @java.lang.Override
    public ReflectAttributeValuesWithTime parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReflectAttributeValuesWithTime> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReflectAttributeValuesWithTime> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hla.rti1516_202X.fedpro.ReflectAttributeValuesWithTime getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

