// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.fedpro;

/**
 * Protobuf type {@code rti1516_202X.fedpro.RtiConfiguration}
 */
public final class RtiConfiguration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti1516_202X.fedpro.RtiConfiguration)
    RtiConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RtiConfiguration.newBuilder() to construct.
  private RtiConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RtiConfiguration() {
    configurationName_ = "";
    rtiAddress_ = "";
    additionalSettings_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RtiConfiguration();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_RtiConfiguration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_RtiConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hla.rti1516_202X.fedpro.RtiConfiguration.class, hla.rti1516_202X.fedpro.RtiConfiguration.Builder.class);
  }

  public static final int CONFIGURATIONNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object configurationName_;
  /**
   * <code>string configurationName = 1;</code>
   * @return The configurationName.
   */
  @java.lang.Override
  public java.lang.String getConfigurationName() {
    java.lang.Object ref = configurationName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configurationName_ = s;
      return s;
    }
  }
  /**
   * <code>string configurationName = 1;</code>
   * @return The bytes for configurationName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigurationNameBytes() {
    java.lang.Object ref = configurationName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configurationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RTIADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object rtiAddress_;
  /**
   * <code>string rtiAddress = 2;</code>
   * @return The rtiAddress.
   */
  @java.lang.Override
  public java.lang.String getRtiAddress() {
    java.lang.Object ref = rtiAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rtiAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string rtiAddress = 2;</code>
   * @return The bytes for rtiAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRtiAddressBytes() {
    java.lang.Object ref = rtiAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rtiAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDITIONALSETTINGS_FIELD_NUMBER = 3;
  private volatile java.lang.Object additionalSettings_;
  /**
   * <code>string additionalSettings = 3;</code>
   * @return The additionalSettings.
   */
  @java.lang.Override
  public java.lang.String getAdditionalSettings() {
    java.lang.Object ref = additionalSettings_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      additionalSettings_ = s;
      return s;
    }
  }
  /**
   * <code>string additionalSettings = 3;</code>
   * @return The bytes for additionalSettings.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdditionalSettingsBytes() {
    java.lang.Object ref = additionalSettings_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      additionalSettings_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configurationName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, configurationName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rtiAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rtiAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(additionalSettings_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, additionalSettings_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configurationName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, configurationName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rtiAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rtiAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(additionalSettings_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, additionalSettings_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hla.rti1516_202X.fedpro.RtiConfiguration)) {
      return super.equals(obj);
    }
    hla.rti1516_202X.fedpro.RtiConfiguration other = (hla.rti1516_202X.fedpro.RtiConfiguration) obj;

    if (!getConfigurationName()
        .equals(other.getConfigurationName())) return false;
    if (!getRtiAddress()
        .equals(other.getRtiAddress())) return false;
    if (!getAdditionalSettings()
        .equals(other.getAdditionalSettings())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONFIGURATIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + getConfigurationName().hashCode();
    hash = (37 * hash) + RTIADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getRtiAddress().hashCode();
    hash = (37 * hash) + ADDITIONALSETTINGS_FIELD_NUMBER;
    hash = (53 * hash) + getAdditionalSettings().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hla.rti1516_202X.fedpro.RtiConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hla.rti1516_202X.fedpro.RtiConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti1516_202X.fedpro.RtiConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti1516_202X.fedpro.RtiConfiguration)
      hla.rti1516_202X.fedpro.RtiConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_RtiConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_RtiConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hla.rti1516_202X.fedpro.RtiConfiguration.class, hla.rti1516_202X.fedpro.RtiConfiguration.Builder.class);
    }

    // Construct using hla.rti1516_202X.fedpro.RtiConfiguration.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      configurationName_ = "";

      rtiAddress_ = "";

      additionalSettings_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hla.rti1516_202X.fedpro.Datatypes.internal_static_rti1516_202X_fedpro_RtiConfiguration_descriptor;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.RtiConfiguration getDefaultInstanceForType() {
      return hla.rti1516_202X.fedpro.RtiConfiguration.getDefaultInstance();
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.RtiConfiguration build() {
      hla.rti1516_202X.fedpro.RtiConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hla.rti1516_202X.fedpro.RtiConfiguration buildPartial() {
      hla.rti1516_202X.fedpro.RtiConfiguration result = new hla.rti1516_202X.fedpro.RtiConfiguration(this);
      result.configurationName_ = configurationName_;
      result.rtiAddress_ = rtiAddress_;
      result.additionalSettings_ = additionalSettings_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hla.rti1516_202X.fedpro.RtiConfiguration) {
        return mergeFrom((hla.rti1516_202X.fedpro.RtiConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hla.rti1516_202X.fedpro.RtiConfiguration other) {
      if (other == hla.rti1516_202X.fedpro.RtiConfiguration.getDefaultInstance()) return this;
      if (!other.getConfigurationName().isEmpty()) {
        configurationName_ = other.configurationName_;
        onChanged();
      }
      if (!other.getRtiAddress().isEmpty()) {
        rtiAddress_ = other.rtiAddress_;
        onChanged();
      }
      if (!other.getAdditionalSettings().isEmpty()) {
        additionalSettings_ = other.additionalSettings_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              configurationName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              rtiAddress_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              additionalSettings_ = input.readStringRequireUtf8();

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object configurationName_ = "";
    /**
     * <code>string configurationName = 1;</code>
     * @return The configurationName.
     */
    public java.lang.String getConfigurationName() {
      java.lang.Object ref = configurationName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configurationName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string configurationName = 1;</code>
     * @return The bytes for configurationName.
     */
    public com.google.protobuf.ByteString
        getConfigurationNameBytes() {
      java.lang.Object ref = configurationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configurationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string configurationName = 1;</code>
     * @param value The configurationName to set.
     * @return This builder for chaining.
     */
    public Builder setConfigurationName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      configurationName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string configurationName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigurationName() {
      
      configurationName_ = getDefaultInstance().getConfigurationName();
      onChanged();
      return this;
    }
    /**
     * <code>string configurationName = 1;</code>
     * @param value The bytes for configurationName to set.
     * @return This builder for chaining.
     */
    public Builder setConfigurationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      configurationName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object rtiAddress_ = "";
    /**
     * <code>string rtiAddress = 2;</code>
     * @return The rtiAddress.
     */
    public java.lang.String getRtiAddress() {
      java.lang.Object ref = rtiAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtiAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rtiAddress = 2;</code>
     * @return The bytes for rtiAddress.
     */
    public com.google.protobuf.ByteString
        getRtiAddressBytes() {
      java.lang.Object ref = rtiAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtiAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rtiAddress = 2;</code>
     * @param value The rtiAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRtiAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rtiAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string rtiAddress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRtiAddress() {
      
      rtiAddress_ = getDefaultInstance().getRtiAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string rtiAddress = 2;</code>
     * @param value The bytes for rtiAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRtiAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rtiAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object additionalSettings_ = "";
    /**
     * <code>string additionalSettings = 3;</code>
     * @return The additionalSettings.
     */
    public java.lang.String getAdditionalSettings() {
      java.lang.Object ref = additionalSettings_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionalSettings_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string additionalSettings = 3;</code>
     * @return The bytes for additionalSettings.
     */
    public com.google.protobuf.ByteString
        getAdditionalSettingsBytes() {
      java.lang.Object ref = additionalSettings_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalSettings_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string additionalSettings = 3;</code>
     * @param value The additionalSettings to set.
     * @return This builder for chaining.
     */
    public Builder setAdditionalSettings(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      additionalSettings_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string additionalSettings = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdditionalSettings() {
      
      additionalSettings_ = getDefaultInstance().getAdditionalSettings();
      onChanged();
      return this;
    }
    /**
     * <code>string additionalSettings = 3;</code>
     * @param value The bytes for additionalSettings to set.
     * @return This builder for chaining.
     */
    public Builder setAdditionalSettingsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      additionalSettings_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti1516_202X.fedpro.RtiConfiguration)
  }

  // @@protoc_insertion_point(class_scope:rti1516_202X.fedpro.RtiConfiguration)
  private static final hla.rti1516_202X.fedpro.RtiConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hla.rti1516_202X.fedpro.RtiConfiguration();
  }

  public static hla.rti1516_202X.fedpro.RtiConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RtiConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<RtiConfiguration>() {
    @java.lang.Override
    public RtiConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RtiConfiguration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RtiConfiguration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hla.rti1516_202X.fedpro.RtiConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

