// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package hla.rti1516_202X.fedpro;

public interface TimeQueryReturnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_202X.fedpro.TimeQueryReturn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool logicalTimeIsValid = 1;</code>
   * @return The logicalTimeIsValid.
   */
  boolean getLogicalTimeIsValid();

  /**
   * <pre>
   * optional, only valid if logicalTimeIsValid == true
   * </pre>
   *
   * <code>.rti1516_202X.fedpro.LogicalTime logicalTime = 2;</code>
   * @return Whether the logicalTime field is set.
   */
  boolean hasLogicalTime();
  /**
   * <pre>
   * optional, only valid if logicalTimeIsValid == true
   * </pre>
   *
   * <code>.rti1516_202X.fedpro.LogicalTime logicalTime = 2;</code>
   * @return The logicalTime.
   */
  hla.rti1516_202X.fedpro.LogicalTime getLogicalTime();
  /**
   * <pre>
   * optional, only valid if logicalTimeIsValid == true
   * </pre>
   *
   * <code>.rti1516_202X.fedpro.LogicalTime logicalTime = 2;</code>
   */
  hla.rti1516_202X.fedpro.LogicalTimeOrBuilder getLogicalTimeOrBuilder();
}
